### ISSUE TITLE
0.19.0 / Firefox 56.0 node fails with Selenium 3.6.0 - WebDriverException: Message: Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/geckodriver#1015]
## System
* Version: 0.19.0
* Platform: Dockerized [node-firefox](https://hub.docker.com/r/selenium/node-firefox/) 3.6.0, Ubuntu 16.04.3 LTS
* Firefox: 56.0
* Selenium: 3.6.0 with python selenium 3.6.0 

## Testcase
https://github.com/mozilla/kuma/pull/4195 is for branch [upgrade_pytest_1308322](https://github.com/mozilla/kuma/tree/upgrade_pytest_1308322), which contains [a script](https://github.com/mozilla/kuma/blob/48dbaf6a9406e94d1dd95af371fb1141be0c6d47/scripts/run_selenium_hub.sh) that runs the Dockerized hub and node. This should work on OSX / Linux with python 2.7.x (``python --version``)

```
git clone https://github.com/mozilla/kuma.git
git checkout upgrade_pytest_1308322
cd kuma
virtualenv venv
source venv/bin/activate
pip install lxml==3.5.0
pip install -r requirements/test.txt
scripts/run_selenium_hub.sh
```

This will start the selenium hub and nodes for Firefox and Chrome. It will run all or most tests successfully against Chrome, and then fail on the first Firefox test.

Here are the [logs from run_selenium_hub.sh](https://gist.github.com/jwhitlock/e7bc2f78ce6dfee10d1edeae568ebb0c), including [logs from the hub](https://gist.github.com/jwhitlock/e7bc2f78ce6dfee10d1edeae568ebb0c#file-output-20171006-txt-L315-L347) and [logs from the firefox node](https://gist.github.com/jwhitlock/e7bc2f78ce6dfee10d1edeae568ebb0c#file-output-20171006-txt-L349-L379).

Here is the [full console log](https://ci.us-west.moz.works/view/MDN/job/mdn_multibranch_pipeline/job/upgrade_pytest_1308322/23/consoleFull) from a test run on Jenkins.

**Comment by curtisy1** [comment]
I can successfully reproduce this with .NET Selenium on a Windows 10 VM running tests through Team Foundation Server. Any idea what may cause this?

**Comment by IreneLynn** [comment]
I also met this issue before, but it's OK now after I re-installing the firefox.

**Comment by andreastt** [comment]
@jwhitlock Could you please attach a [trace-level log] from geckodriver?

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md

**Comment by whimboo** [comment]
Also as side note given that you are using docker please be aware of https://github.com/mozilla/geckodriver/issues/285#issuecomment-300617774. If that is not set for your docker instance, you should do it. Otherwise Firefox is most likely crashing.

**Comment by rashaverak** [comment]
same issue with

Java selenium-server-standalone-3.6.0.jar
Firefox 56
Gecko driver 0.19 win-64

**Comment by rashaverak** [comment]
So the issue is with 64 windows build of gecko which is probably some kind of a joke build, it does not even handle /session command with {"capabilities": {"alwaysMatch": {"acceptInsecureCerts": true}}} responding that session is unknown command, win 32 works fine.

btw v64 win does not work even with gecko 18

**Comment by rashaverak** [comment]
Continue testing the capabilities which set up the java client, this is still wrong

{"capabilities": {"alwaysMatch": {"acceptInsecureCerts": true, "browserName":"firefox",  
"moz:firefoxOptions":{"args":[], "log":{"level":"trace"}, "binary":"path", "profile":"name"}}}}

**Comment by whimboo** [comment]
I'm not sure what you expect when passing in `path` as binary. It should be a real path to the binary. The failure message can definitely be better. I filed a bug for geckodriver to improve the message.

**Comment by jwhitlock** [comment]
@andreastt sorry, there's not much change in ``geckodriver`` with trace level logging, and I'm not sure if I did it right.

I tried two things:

**Update the node-firefox configuration** to include ``"alwaysMatch": {"moz:firefoxOptions": {"log": {"level": "trace"}}},``. I did this by creating a custom Docker image of NodeFirefox from https://github.com/SeleniumHQ/docker-selenium. I'll open a PR to make this possible without the custom image.

**Set trace logging** in the tests. I'm using [pytest-selenium](http://pytest-selenium.readthedocs.io/en/latest/user_guide.html#configuration-files), so I added this to a test file:

```
@pytest.fixture
def firefox_options(firefox_options):
    firefox_options.log.level = 'trace'
    return firefox_options
```

The logging level shows up in the test output:
```
driver_kwargs = {'browser_profile': None, 'command_executor': 'http://hub:4444/wd/hub', 'desired_capabilities': {'browserName': 'firefox', 'moz:firefoxOptions': {'log': {'level': 'trace'}}, 'platform': 'ANY', 'version': ''}}
```

and in the hub output:
```
14:10:49.499 INFO - Mismatched capabilities. Creating a synthetic w3c capability.
14:10:49.505 INFO - Got a request to create a new session: Capabilities [{browserName=firefox, moz:firefoxOptions={log={level=trace}}, platformName=ANY, version=, platform=ANY}]
14:10:49.506 INFO - Trying to create a new session on test slot {seleniumProtocol=WebDriver, browserName=firefox, alwaysMatch={moz:firefoxOptions={log={level=trace}}}, maxInstances=1, version=56.0, applicationName=, platform=LINUX}
```

and in the node-firefox output, but geckodriver still isn't being any more chatty:
```
14:10:49.625 INFO - Mismatched capabilities. Creating a synthetic w3c capability.
14:10:49.633 INFO - Capabilities are: Capabilities {browserName=firefox, moz:firefoxOptions={log={level=trace}}, platformName=ANY, version=, platform=ANY, }
14:10:49.636 INFO - Capabilities {browserName=firefox, moz:firefoxOptions={log={level=trace}}, platformName=ANY, version=, platform=ANY, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
14:10:49.636 INFO - Capabilities {browserName=firefox, moz:firefoxOptions={log={level=trace}}, platformName=ANY, version=, platform=ANY, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
14:10:49.636 INFO - Capabilities {browserName=firefox, moz:firefoxOptions={log={level=trace}}, platformName=ANY, version=, platform=ANY, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
1508767849662	geckodriver	INFO	geckodriver 0.19.0
1508767849665	geckodriver	INFO	Listening on 127.0.0.1:31098
```

Here's the [full output](https://gist.github.com/jwhitlock/ea46c2c20c614e48d63e147d0277d080).

**Comment by jwhitlock** [comment]
@whimboo thanks for the suggestion, but adding ``--shm-size 2g`` appeared to have no effect. I still get the "Mismatched capabilities" error. Here's [the log](https://gist.github.com/jwhitlock/4be6a4f468e7e4b19ea4254c151afdd4).

**Comment by jwhitlock** [comment]
@rashaverak my issue is for Selenium hub / node. My tests work locally when I run them against Firefox 56.0 with geckodriver 0.19.0. You may want to open a new issue.

**Comment by rashaverak** [comment]
It is the same issue, selenium hub is innocent here, the issue is the same if you call directly geckodriver.

Also I can hardly pass binary data in json, so what else should I send instead of path to the binary ? And anyway it is java client which sends it, not me, I just took it and did some direct requests to test what is wrong.

**Comment by whimboo** [comment]
Please note that we currently return a "Unable to find a matching set of capabilities" error if the Firefox binary cannot be found. See [bug 1410838](https://bugzilla.mozilla.org/show_bug.cgi?id=1410838) for details.

@jwhitlock, is the Firefox binary in your PATH environment variable? If not, you will have to specify it separately via the `binary` key inside firefox_options. See https://github.com/mozilla/geckodriver#firefox-capabilities.

**Comment by jwhitlock** [comment]
It is in the path:
```
seluser@d4e7c92b9400:/$ which firefox
/usr/bin/firefox
seluser@d4e7c92b9400:/$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

Here's the configuration of the two nodes:

<img width="825" alt="selenium node config" src="https://user-images.githubusercontent.com/286017/32104664-09e081c8-baeb-11e7-9170-500abcf17108.png">

**Comment by kadung** [comment]
I also occurs the same issue with Java binding, caps matching seems OK but Selenium node does not start Firefox and after that Selenium hub complains that it cannot establish new session. Below is the log from node, I also try to get the geckodriver log but that's all I can get for now.
**Test Code**
```
package example;

import java.net.URL;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.annotations.Test;
import org.openqa.selenium.Platform;

public class issue {
	@Test
        public void google() throws Exception { 
    	    URL seleniumGridURL = new URL("http://192.168.1.103:4444/wd/hub");
    	    DesiredCapabilities capabilities = DesiredCapabilities.firefox();
    	    capabilities.setPlatform(Platform.valueOf("VISTA"));
    	    WebDriver driver = new RemoteWebDriver(seleniumGridURL, capabilities);
    	    driver.get("http://www.google.com");
   }
}
```
**Hub log:**

> 21:34:57.878 INFO - Got a request to create a new session: Capabilities [{acceptInsecureCerts=true, browserName=firefox, moz:firefoxOptions={args=[], log={level=error}, prefs={}}, platformName=VISTA, version=, platform=VISTA}]
> 21:34:57.879 INFO - Trying to create a new session on test slot {seleniumProtocol=WebDriver, browserName=firefox, maxInstances=5, platform=VISTA}
> 21:44:43.042 INFO - Marking the node http://192.168.254.128:5555 as down: cannot reach the node for 2 tries

**Node log**

> 22:29:25.881 INFO - Binding default provider to: org.openqa.selenium.chrome.ChromeDriverService
22:29:25.881 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.BeginSession@1d19374
22:29:25.897 INFO - /session: Executing POST on /session (handler: BeginSession)
22:29:25.897 INFO - Mismatched capabilities. Creating a synthetic w3c capability.
22:29:25.897 INFO - Capabilities are: Capabilities {acceptInsecureCerts=true, browserName=firefox, platformName=VISTA, version=, platform=VISTA, }
22:29:25.897 INFO - Capabilities {acceptInsecureCerts=true, browserName=firefox, platformName=VISTA, version=, platform=VISTA, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
22:29:25.897 INFO - Capabilities {acceptInsecureCerts=true, browserName=firefox, platformName=VISTA, version=, platform=VISTA, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
**It stucks here**

**Comment by whimboo** [comment]
Can you both please try to use the `binary` key of the `moz:firefoxOptions` capability? When specifying the exact path there, does it work?

**Comment by kadung** [comment]
**Test script:**
> @Test
    public void google() throws Exception { 
    	URL seleniumGridURL = new URL("http://192.168.1.103:4444/wd/hub");
    	DesiredCapabilities capabilities = DesiredCapabilities.firefox();
    	FirefoxOptions options = new FirefoxOptions();
        options.setBinary("C:/Program Files/Mozilla Firefox/firefox.exe");
        capabilities.setCapability(FirefoxOptions.FIREFOX_OPTIONS, options);
    	capabilities.setPlatform(Platform.valueOf("VISTA"));
    	WebDriver driver = new RemoteWebDriver(seleniumGridURL, capabilities);
    	driver.get("http://www.google.com");
    	driver.close();
    	driver.quit();
   }

**Node log**
> 2017-11-01 23:45:09.441:INFO:osjshC.ROOT:qtp7526964-11: org.openqa.selenium.remote.server.WebDriverServlet-1c758ac: Initialising WebDriverServlet
23:45:09.488 INFO - Binding default provider to: org.openqa.selenium.chrome.ChromeDriverService
23:45:09.503 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.BeginSession@a544f9
23:45:09.534 INFO - /session: Executing POST on /session (handler: BeginSession)
23:45:09.737 INFO - Mismatched capabilities. Creating a synthetic w3c capability.
23:45:09.768 INFO - Capabilities are: Capabilities {firefox_binary=C:/Program Files/Mozilla Fi..., acceptInsecureCerts=true, browserName=firefox, moz:firefoxOptions={args=[], binary=C:/Program Files/Mozilla Fi..., prefs={}, }, platformName=VISTA, version=, platform=VISTA, }
23:45:09.768 INFO - Capabilities {firefox_binary=C:/Program Files/Mozilla Fi..., acceptInsecureCerts=true, browserName=firefox, moz:firefoxOptions={args=[], binary=C:/Program Files/Mozilla Fi..., prefs={}, }, platformName=VISTA, version=, platform=VISTA, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
23:45:09.768 INFO - Capabilities {firefox_binary=C:/Program Files/Mozilla Fi..., acceptInsecureCerts=true, browserName=firefox, moz:firefoxOptions={args=[], binary=C:/Program Files/Mozilla Fi..., prefs={}, }, platformName=VISTA, version=, platform=VISTA, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
23:45:09.768 INFO - Capabilities {firefox_binary=C:/Program Files/Mozilla Fi..., acceptInsecureCerts=true, browserName=firefox, moz:firefoxOptions={args=[], binary=C:/Program Files/Mozilla Fi..., prefs={}, }, platformName=VISTA, version=, platform=VISTA, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
**Still stuck in here**


**Console log**
> FAILED: google
org.openqa.selenium.SessionNotCreatedException: Cannot establish new session
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: 'WIN-APD1CKCJ4A3', ip: '192.168.254.129', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_144'
Driver info: driver.version: unknown
Command duration or timeout: 53.40 seconds
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$24(ProtocolHandshake.java:359)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:362)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:136)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:586)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:217)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:140)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:153)
	at example.issue.google(issue.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: org.openqa.selenium.SessionNotCreatedException: Cannot establish new session
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T16:15:40.131Z'
System info: host: 'WIN-APD1CKCJ4A3', ip: '192.168.254.129', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_144'
Driver info: driver.version: unknown
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'DESKTOP-EH10K5M', ip: '192.168.254.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: driver.version: unknown
	at org.openqa.selenium.remote.server.ServicedSession$Factory.apply(ServicedSession.java:215)
	at org.openqa.selenium.remote.server.ActiveSessionFactory.lambda$createSession$16(ActiveSessionFactory.java:171)
	at java.util.Optional.map(Unknown Source)
	at org.openqa.selenium.remote.server.ActiveSessionFactory.createSession(ActiveSessionFactory.java:171)
	at org.openqa.selenium.remote.server.commandhandler.BeginSession.execute(BeginSession.java:72)
	at org.openqa.selenium.remote.server.WebDriverServlet.lambda$handle$0(WebDriverServlet.java:232)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by whimboo** [comment]
@kadung, any reason why the log is showing up the usage of `chrome.ChromeDriverService` and `firefox.GeckoDriverService`? Are you mixing up different drivers here?

**Comment by kadung** [comment]
No @whimboo I only run firefox on the node, testscript run directly with testng. I look over the internet and it seems normal: https://github.com/mozilla/geckodriver/issues/889

**Comment by andreastt** [comment]
@jwhitlock We need you to produce a trace a [trace-level log] from geckodriver. Apparently some of the plethora of middle-ware dependencies you use interfere with the capabilities passed to geckodriver, which is why `{"alwaysMatch": {"moz:firefoxOptions": {"log": {"level": "trace"}}}` fails for you.

You say that the test output shows this:

> driver_kwargs = {'browser_profile': None, 'command_executor': 'http://hub:4444/wd/hub', 'desired_capabilities': {'browserName': 'firefox', 'moz:firefoxOptions': {'log': {'level': 'trace'}}, 'platform': 'ANY', 'version': ''}}

I’m assuming this is passed to your Selenium Grid intermediary proxy, but you don’t include what JSON body is actually passed to the geckodriver HTTPD. Because the proxy somehow interferes with the JSON body you need to either instrument Selenium Grid so it logs the actual HTTP request it makes to geckodriver, or start the geckodriver process with the `-vv` flag, which overrides the `moz:firefoxOptions` key for enabling trace logs.

A few random observations about what I see in the above `driver_kwargs` dictionary:

* I’m assuming `desired_capabilities` is picked up by some intermediary node and gets translated in to a `desiredCapabilities` object passed on to geckodriver. `desiredCapabiltiies` is the old Selenium-styled way of passing capabilities and it should use a `{"capabiliites": {"moz:firefoxOptions": …}}` top-level object instead.
* `moz:firefoxOptions` is only picked up when using W3C WebDriver-conforming New Session requests, i.e. a top-level `capabilities` object.
* Similarly, `platform` is an unrecognised capability, but again I’m assuming you have some middle-ware code that translates that into `platformName` that gets merged into `desiredCapabilities`. `ANY` is not a valid value for this.
* This also applies for `version`.

You can read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://searchfox.org/mozilla-central/source/testing/geckodriver/doc/TraceLogs.md
[contribution guidelines]: https://searchfox.org/mozilla-central/source/testing/geckodriver/CONTRIBUTING.md#reporting-bugs

**Comment by jwhitlock** [comment]
Thanks for everyone's help. Fixed with upgrade to:

* [selenium 3.7.0](https://pypi.python.org/pypi/selenium/3.7.0)
* [bug 3.7.1-argon](https://hub.docker.com/r/selenium/hub/tags/)
* [node-chrome](https://hub.docker.com/r/selenium/node-chrome/tags/)
* [node-firefox 3.7.1-argon](https://hub.docker.com/r/selenium/node-firefox/tags/), which includes Firefox 56.0.2 and geckodriver 0.19.1

Tests pass in Chrome, with one flaky test due to a recent change. Tests run in Firefox, with 5 failures, which gets me back to where I was with Selenium 3.5.

It may be worth working with the [docker-selenium team](https://github.com/SeleniumHQ/docker-selenium) to get Firefox w/ the Remote driver into their test matrix, and to add hooks for the debugging tracebacks you need for actionable bugs.

**Comment by whimboo** [comment]
@jwhitlock do you know which of those upgrades actually fixed it? I would be interested in just in-case of other possible reports.

**Comment by jwhitlock** [comment]
I started my attempt to update to Selenium 3 with Selenium 3.4:

| Selenium | Firefox | Local Chrome | Local Firefox | Remote Chrome | Remote Firefox |
| -------- | --- | ------------ | ------------- | ------------- | -------------- |
| 2.53.1 | 47.0.1 | ✅  | ✅  | Not Attempted | ✅ |
| 3.4 | 55.0 | ✅ | ✅ | ✅ | ❌ Can't run tests (https://github.com/SeleniumHQ/selenium/issues/3927) |
| 3.5 | 55.0.3 | ✅ | 2 Tests Fail (fixed) | ✅   | Many Tests Fail |
| 3.6 | 56.0.2 | ✅  | ✅ | ✅ | ❌ Can't run tests (this bug) |
| 3.7 | 56.0.2 | ✅ | ✅ | ✅ | 6 Tests Fail |

I suspect core Selenium breaks *something* in the even releases, and the libraries (or geckodriver or Firefox) catch up in the odd releases. I haven't seen any good candidates in the release notes for what fixed it, and I'm not following Selenium development closely, just updating to latest versions of everything so I have a better chance of having the same environment as the Selenium devs.

**Comment by andreastt** [comment]
It would be good if you could drill down to what the underlying problems are and file specific bugs for them where appropriate.
