### ISSUE TITLE
Implement locator strategy using id

### ISSUE THREAD

**Issue by sherlock1982** [mozilla/geckodriver#1041]
I recently switched from Selenium to using geckodriver directly and found out that geckodriver doesn't allow "id" locator strategy when looking for elements.

Well I understand that it's not in W3C but it's very easy to implement and than switching to geckodriver will be much easier. Just add # and interpret it as a CSS selector.

Selenium, chromedriver and others I believe support it. So many Selenium clients will be easier to adapt to geckodriver.

**Comment by jimevans** [comment]
I’m not a contributor to the geckodriver project, but I am a contributor to the spec. The location strategy isn’t in the spec, for exactly the reason you note, that it’s incredibly easy to model using CSS selectors. For spec-compliant remote ends, Selenium language bindings fake finding by ID by doing exactly what you suggest, so the transition is seamless for Selenium users. If you’re using a language binding not supplied by the Selenium project, or using some other local end to the wire protocol, my advice would be to have the maintainers of that library mock finding by ID in the same way.

**Comment by sherlock1982** [comment]
I'm using WebdriverIO. They already [declined](https://github.com/webdriverio/webdriverio/issues/2392) motivating that lots of drivers support this strategy and they won't break tests because geckodriver doesn't support it.

Well yes there are app layer workarounds but on the other hand they claim W3C compatibility so it's a kind of a contradiction to me.

**Comment by andreastt** [comment]
WebDriver doesn’t include an element-by-ID selector precisely because it is easy to replicate using a CSS selector using `#` appended by the element ID. The idea is that Selenium should provide a shim that converts API calls using the ID selector to a CSS selector, before passing the command on to geckodriver.

I would appreciate if you would file a bug with WebDriverIO

I would encourage you to push back with WebDriverIO because soon all drivers will be W3C conforming. chromedriver has their conforming behaviour hidden behind a flag for the moment, and they will similarly face the same problem when someone tries using their new driver with WebDriverIO. 

EdgeDriver and the new IEDriver similarly do not implement an ID selector and faces the same issue. The reason this looks like a geckodriver-only problem is because the lack of a legacy FirefoxDriver that works with modern Firefoxen, causing geckodriver to be the only alternative.

**Comment by whimboo** [comment]
@andreastt, do we really have to keep this issue open? There is nothing we are waiting for from the Selenium project, and what we do is what the spec defines.
