### ISSUE TITLE
org.openqa.selenium.InvalidArgumentException: File not found: C:\test-folder. When trying to upload a folder with sendKeys("folder-path")

### ISSUE THREAD

**Issue by bogdanbocancea** [mozilla/geckodriver#1069]
## System
* Version: 0.19.1
* Platform: Windows 10
* Firefox: 57.0 / 58.0b5 
* Selenium: 3.7.1

## Testcase
Try to upload a folder with .sendKeys("folder-path")

**Comment by whimboo** [comment]
The information you have specified are far from complete. A code example is missing, and what is more important a [trace log](https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html).

I just tried it myself and it works just fine with latest geckodriver and each version of Firefox down to at least 57.:

```
    def test_hang_sendkeys(self):
        self.driver.get(self.inline("""<input type="file">"""))
        input = self.driver.find_element_by_css_selector("input")
        input.send_keys("/data/testcase.html")
 ```

In case you can provide a trace log we can reopen the issue. Otherwise there is nothing actionable here.

**Comment by whimboo** [comment]
It still works for me with a path. The failure I get is `WebDriverException: Message: File not found: /data/`. Maybe this is a Windows only issue?

Also the log is not a trace log. Please check my link above again. Providing such a log would help us a lot. Thanks.

**Comment by bogdanbocancea** [comment]
I've uploaded the trace log.
So, I have a test that is uploading a folder from disk with multiple sub-folders and sub-files. This test is working with chromedriver, no error is thrown.
The thing is I want to avoid the failure '_WebDriverException: Message: File not found: /data/_' and upload the folder successfully in the application.

**Comment by whimboo** [comment]
Ok, so I had another look and based on your last reply you don't want to see this failure for folders being uploaded.

Thing is that chromedriver is not webdriver spec conformant, and I don't know which behavior got implemented in that version you are using, but a path is not allowed as input. Instead a list of files has to be specified, and passed in as a multi-line string. 

@andreastt can you please crosscheck? But I strongly feel this issue is invalid.

**Comment by ehtishammalik** [comment]
I am facing the same issue with chromedriver. I am running the tests from the Linux OS and its giving me the same error
`selenium.common.exceptions.WebDriverException: Message: invalid argument: File not found : \home\hamza\Wukla\bdd-testing\paksign\test_files\test1
  (Session info: chrome=68.0.3440.75)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-29-generic x86_64)`

**Comment by ali0646** [comment]
I am facing the same issue on chromedriver. Does anyone have any solution to it?
