### ISSUE TITLE
Unable to view flash content in the Selenium launches firefox 57

### ISSUE THREAD

**Issue by michealarun** [mozilla/geckodriver#1103]
## System
* Version: 
* Platform: 
* Firefox: 
* Selenium:

**Comment by andreastt** [comment]
You didn’t fill in any of the required template information, however, we disable Flash explicitly because it is known to cause problems when quitting Firefox from geckodriver, see for example https://github.com/mozilla/geckodriver/issues/225.

You can set the `plugin.state.flash` preference to `1` to override this behaviour and enable Flash.
