### ISSUE TITLE
Digitally Sign Windows Binary

### ISSUE THREAD

**Issue by bloudraak** [mozilla/geckodriver#1116]
## System
* Version: 0.19.1
* Platform: Windows (both 64bit + 32bit)
* Firefox: N/A
* Selenium: N/A

## Testcase

* Download the binary from GitHub Releases.
* Extract the archive
* Navigate to the binary
* Right Click on the binary, select Properties and look at the Details tab

## Stacktrace
N/A

## Trace-level log
N/A
 
## Rationale

When using the gecko driver with Selenium in a "security sensitive" environment, like that of government,  healthcare or finance, it is critical for the user to be able to prove the integrity and reputation of the binary.  This means that when we download the binary, we could validate that it was produced by Mozilla and that it still has a good reputation (since the certificate is still valid).  Consider what would happen if someone was able to upload a new binary with a backdoor. (this happened to a [Linux Distro](https://www.techworm.net/2016/02/hacker-explains-put-backdoor-linux-mint-downloads.html) in 2016).

This is a nice write up on why it is useful:
https://blogs.msdn.microsoft.com/ieinternals/2011/03/22/everything-you-need-to-know-about-authenticode-code-signing/

Note that firefox.exe is digitally signed.

**Comment by andreastt** [comment]
Not sure exactly what you’re asking for, but there is https://github.com/mozilla/geckodriver/issues/292 for providing checkedsummed packages which I thinks is reasonable and which would resolve all the concerns you would have?

**Comment by bloudraak** [comment]
Checksums are not a security feature. They only provide the ability for the user to validate that their download was not corrupted.  An attacker who is able to replace a binary also is able to replace the checksum. It offers no guarantee of security.  The solution offered in #292 misses the requirement to prove the integrity and validate the reputation of the binary.

**Comment by andreastt** [comment]
Thanks for the correction. From the documentation you linked I see that ‘Authenticode Code Signing’ is a Windows concept that is different to computing the binary’s checksum.

I don’t object to receiving a patch that signs the Windows binary, but because we cross-compile geckodriver for Windows on Linux it can be difficult to get access to `SignTool.exe`. I found [a discussion in the Rust user forums](https://users.rust-lang.org/t/windows-authenticode-publisher-signing/11668) that asks if it cargo is able to do it, and if cargo were to support it directly, it would be easier to support.

<hr>

Checksums _by themselves_ don’t offer security, just like a certificate doesn’t unless you trust the issuer. It does however provide a mechanism for users and package managers to verify against a Mozilla-approved source (such as a list of checksums in the release announcement email) that downloaded geckodriver was made by us.

We don’t maintain any distro packages or “downloaders” for geckodriver, but we welcome people to repackage geckodriver for distribution. If done correctly a checksum would be useful in determining that the binary was made by us.

**Comment by bloudraak** [comment]
I provided the Linux Mint use case as a reason why the following may not hold:

> We don’t maintain any distro packages or “downloaders” for geckodriver, but we welcome people to repackage geckodriver for distribution. If done correctly a checksum would be useful in determining that the binary was made by us.

If for any reason, an attacker gets hold of credentials to replace or upload binaries, they can replace the checksum alongside with the binary.  

Most common checksums (SHA1, MD4, SHA256) are good only to see if the download is corrupt or not, it offers me no ability to attest that the binaries were produced by Mozilla and Mozilla alone.

**Comment by bloudraak** [comment]
While I can offer you the command line and even donate money for the signing certificate (~$250/year), the most important part of the signing process is that access to the certificate is restricted, (often) only exists on your build servers and that administrative access to the build server is restricted too.  The same applies to OpenPGP. The private key should not be made available.

So from a contribution perspective, I can't the keys or certificates themselves, that will introduce a weakness (in case my computer ever gets hacked).  I can offer you the commands I ran to sign the binaries.

Is the geckodriver being built on the same build infrastructure as Firefox? Is there a possibility for Mozilla to sign the binaries using the same keys as for Firefox?

**Comment by whimboo** [comment]
Yes, we should be able to. But I don't know how complicated it is. I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1427849 to handle it.

**Comment by bloudraak** [comment]
Assuming you have the Windows SDK installed and that there is only one code signing certificate installed, after building the binary, the command to sign hello.exe look as follows on my build server. 

```
cd c:\path\to\hello
signtool sign /sm /tr http://timestamp.digicert.com /td sha256 /fd sha256 /a hello.exe
```

I have a code signing certificate from digicert, hence the use of http://timestamp.digicert.com. It differs for different certificate authorities.

**Comment by JohanLorenzo** [comment]
Hi there! Thank you for filing this issue. [Bug 1427849](https://bugzilla.mozilla.org/show_bug.cgi?id=1427849) will take care of signing the binaries (of Windows, Mac, and Linux).

In the meantime, we can mitigate the risks by gpg-signing a checksum file. This way, you're sure the checksum given comes from a trusted party and the intended file hasn't changed, since it was originally published. As of today, sha256 is cryptographically good enough to ensure a hash unique.
This is simple enough to set up, on our end and isn't specific to any platform.

Would such a solution work for you @bloudraak?

**Comment by bloudraak** [comment]
@JohanLorenzo It would work for downloads. 

Do you have any documentation how one would specifically validate the download using this approach as part of a bash script? That script can be adapted for PowerShell later.

**Comment by JohanLorenzo** [comment]
I'm sorry for the delay. The procedure would be quite standard in the GPG world. In short, this would be:

# A. Init (do it once)

1. Install a gpg client on your target machine
1. Download the public key. You need the owner to communicate their public key directly, or you need them to upload the key on a server (like https://gpg.mozilla.org/) and tell you their fingerprint. The communication must happen from a channel you trust. Ideally you would communicate in person, but this can be github commit signed by their account.
1. Import the public key. `gpg --import public.asc`
1. Set the trust level to `full` (that explains the precautions on step 1). `gpg --edit-key $fingerprint` => `trust` => `4`

# B. Signature verification (do it on every new release)

1. Download the archive, its checksum and the signature of its checksum.
1. `gpg --verify $file_of_signature_of_checksum`
1. If signature was trusted, then you can run the checksum against the real file.

# Extra notes

Both part A and B are small shell commands. They can definitely fit in a script. I'd recommend to start with part B first, because it's the one that doesn't require human interactions/judgment. What do you think @bloudraak ? 

# References
* qubes OS about importing their public key https://www.qubes-os.org/security/verifying-signatures/#importing-qubes-signing-keys
* qubes OS about checking sums https://www.qubes-os.org/security/verifying-signatures/#verifying-digests 
* Debian about generating keys https://wiki.debian.org/Keysigning

**Comment by bloudraak** [comment]
This is great for testing the authenticity of the download. Thanks! 

On Windows, we’ll still need to sign the binary so Security products doesn’t prevent it from being executed. Are we keeping the issue open until the defect mentioned above is addressed and verified?

**Comment by whimboo** [comment]
Yes, we keep it open until the bug is fixed.

**Comment by whimboo** [comment]
> Hi there! Thank you for filing this issue. [Bug 1427849](https://bugzilla.mozilla.org/show_bug.cgi?id=1427849) will take care of signing the binaries (of Windows, Mac, and Linux).

Signing of Windows and Mac builds has been done in our CI for the toolchain generated binaries. And with the upcoming 0.27 release we will ship those via Github.
