### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: connection refused

### ISSUE THREAD

**Issue by markostanojlovic** [mozilla/geckodriver#1117]
## System
* Version: v0.19.1 (and 0.19.0, with 0.18.0 error is not present)
* Platform: Linux SLES 12 SP3 
* Firefox: 52.5.0
* Selenium: 3.8.0 python bindings 

## Testcase

    from selenium import webdriver
    driver = webdriver.Firefox()

## Stacktrace

No errors in geckodriver.log:

    1514659027040	geckodriver	INFO	geckodriver 0.19.1
    1514659027046	geckodriver	INFO	Listening on 127.0.0.1:42148
    1514659028132	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.67z4on8W5Y26"
    1514659031076	Marionette	INFO	Listening on port 2828

## Trace-level log
no trace log

**Comment by andreastt** [comment]
I don’t see any immediate problems in the log you attached, but Firefox 52 isn’t supported by geckodriver. Not really sure what the problem here is.

**Comment by sharatkanthi** [comment]
0
down vote
-This could be for various reasons.

-Most probably because the "latest" version of your geckodriver is not able to communicate with your "slightly older" firefox.

-The easiest way to fix this would be to try out different older versions of geckodriver. Run the following command to find the current version of your geckodriver

geckodriver --version

-If it shows the version as 19 or above, execute following steps to use geckodriver version 17(Works 90% of times)

-Step 1: Your existing geckodriver most typically may be placed in /usr/local/bin when u installed it earlier. First delete this by running sudo rm -r /usr/local/bin/geckodriver

-Step 2: Download version 17 of geckodriver from following link

https://github.com/mozilla/geckodriver/releases/tag/v0.17.0

Move the download file(geckodriver-v0.17.0-arm7hf.tar.gz) from your "Downloads" folder into your "home" directory

-Step 3: Unpack the file

tar -xzvf geckodriver-v0.17.0-arm7hf.tar.gz `

This will create a folder called "geckodriver" in your home directory

-Step 4: Move/Copy this extracted "geckodriver" into /usr/local/bin/

sudo cp geckodriver /usr/local/bin/

-Step 5: Run sudo reboot

rerun your program now... It should work
