### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: connection refused

### ISSUE THREAD

**Issue by gitsnippet** [mozilla/geckodriver#1136]
## System
* Version:  v 0.19.1 
* Platform:  debian9
* Firefox:   52.4.0(64bit)
* Selenium:       3.8

## invoke firefox
from selenium import webdriver
browser = webdriver.Firefox()

firefox opened, an error occur as below:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/webdriver.py", line 158, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

**Comment by andreastt** [comment]
Firefox 52 isn’t supported.

**Comment by whimboo** [comment]
Just to add, you need at least Firefox 55 when using geckodriver 0.19.1, as stated in the documentation.

**Comment by sharatkanthi** [comment]
0
down vote
-This could be for various reasons.

-Most probably because the "latest" version of your geckodriver is not able to communicate with your "slightly older" firefox.

-The easiest way to fix this would be to try out different older versions of geckodriver. Run the following command to find the current version of your geckodriver

geckodriver --version

-If it shows the version as 19 or above, execute following steps to use geckodriver version 17(Works 90% of times)

-Step 1: Your existing geckodriver most typically may be placed in /usr/local/bin when u installed it earlier. First delete this by running sudo rm -r /usr/local/bin/geckodriver

-Step 2: Download version 17 of geckodriver from following link

https://github.com/mozilla/geckodriver/releases/tag/v0.17.0

Move the download file(geckodriver-v0.17.0-arm7hf.tar.gz) from your "Downloads" folder into your "home" directory

-Step 3: Unpack the file

tar -xzvf geckodriver-v0.17.0-arm7hf.tar.gz `

This will create a folder called "geckodriver" in your home directory

-Step 4: Move/Copy this extracted "geckodriver" into /usr/local/bin/

sudo cp geckodriver /usr/local/bin/

-Step 5: Run sudo reboot

rerun your program now... It should work

**Comment by andreastt** [comment]
Please let’s not resurrect old, resolved issues. If you have new issues, please file _new_ issues.
