### ISSUE TITLE
Version Matcher - Firefox and Geckodriver

### ISSUE THREAD

**Issue by lucasmello** [mozilla/geckodriver#1153]
It would be nice to have a clear changelog to make it easier to know which Firefox versions work best with which Geckodriver version. I'm currently working on a project that automates the driver download [(driloader)](https://github.com/lucasmello/Driloader/) and we are able to get the Chromedriver version in [Chrome Release Notes](https://chromedriver.storage.googleapis.com/2.35/notes.txt) but it's really hard to get the best Geckodriver to the user based on his Firefox instalation.

Is there any chance to have this organized version matcher?

**Comment by andreastt** [comment]
This is documented in the [README](https://github.com/mozilla/geckodriver#supported-firefoxen) and the [change log](https://searchfox.org/mozilla-central/source/testing/geckodriver/CHANGES.md) does contain this information.

**Comment by timothyjmtan** [comment]
Hi,

I am also searching for the same thing, but am unable to find it in the change log. I do see the latest release being 0.23.0, but am not sure what versions of Firefox does this driver support? This is of great usefulness, if not I wouldn't be able to see if it's the root cause of an issue I'm facing.
Are you guys able to include the supported versions in future change logs?

**Comment by timothyjmtan** [comment]
I'm not sure how to reopen this ticket, and if anyone will read comments from closed issues.

**Comment by whimboo** [comment]
There is https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Support.html nowadays which informs exactly about that.

**Comment by timothyjmtan** [comment]
Wow exactly what I need. Thank you!

**Comment by lucasmello** [comment]
Thanks, it helps me a lot too!
