### ISSUE TITLE
org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session.

### ISSUE THREAD

**Issue by chakravarthy** [mozilla/geckodriver#1182]
## System

* Version: geckodriver: 0.19.1
* Platform: Linux: Ubuntu 14.04
* Firefox: 59.0b8 (64-bit)
* Selenium: 3.9.1

## Testcase

public class Grid_SetUp {
        public static RemoteWebDriver driver;

        public static void main(String[]  args) throws InterruptedException{
        String serverURL = "http://google.com";
        String Node = "http://<IP of selenium hub>:4444/wd/hub";
        DesiredCapabilities capabilities = DesiredCapabilities.firefox();
        System.setProperty("webdriver.gecko.driver","/home/user/Grid_Test/Node/geckodriver");
        //capabilities.setCapability("webdriver.gecko.driver", "/home/user/Grid_Test/Node/geckodriver");
        driver = new RemoteWebDriver(new URL(Node), capabilities);
        driver.navigate().to(serverURL);
        Thread.sleep(10000);
        driver.quit();
        }
}

Note:
Selenium Grid Hub and Node both are running and Node is registered to Hub.
Two Firefox windows opens up one after the other and execution stops.
Same code works well for chrome, if I replace firefox with chrome in DesiredCapabilities.firefox(); and remove geckodriver system property.

On debuging saw that call to createSession(client, parameters); in ProtocolHandshake.class returns Optional.empty and hence the problem, but not sure why it is returning empty.

## Stacktrace

Feb 16, 2018 3:16:51 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
Feb 16, 2018 3:19:01 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Falling back to original OSS JSON Wire Protocol.
Feb 16, 2018 3:19:08 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Falling back to straight W3C remote end connection
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{marionette=true, browserName=firefox, version=, platform=ANY}], required capabilities = Capabilities [{}]
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'use-BLTSP02260', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.16.0-30-generic', java.version: '1.8.0_141'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:91)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:155)
	at Grid_SetUp.main(Grid_SetUp.java:115)

**Comment by schmidtkp** [comment]
@andreastt I'm also seeing this issue with v0.19.1 and v0.20.0 (and FF v59.0). It only happens when I use `RemoteWebDriver` (possibly client-binding issue?). I have a locally configured hub/node running on a MBP.

As for trace-level logs I only get the following in the console when calling RemoteWebDriver (from within IntelliJ):

```
1521062561400	geckodriver	INFO	geckodriver 0.20.0
1521062561409	geckodriver	INFO	Listening on 127.0.0.1:27325
```
I'm confident I have trace-level logs set properly (I'm using Java client bindings), as I get the following trace (see below) when I call `FirefoxDriver(FirefoxOptions)` which works correctly, using this code snippet:

```
System.setProperty("webdriver.gecko.driver", "/var/folders/99/kx9d7lpx7s5258rq49tpgs1s56bn5m/T/geckodriver_mac");
FirefoxOptions firefoxOptions = new FirefoxOptions();
firefoxOptions.setLogLevel(FirefoxDriverLogLevel.TRACE);
FirefoxDriver firefoxDriver = new FirefoxDriver(firefoxOptions);
firefoxDriver.get("https:www.google.com");
firefoxDriver.quit();
```

**Trace-level Log for `FirefoxDriver(firefoxOptions)` Call:**

1521063058250	geckodriver	INFO	geckodriver 0.20.0
1521063058257	geckodriver	INFO	Listening on 127.0.0.1:7753
1521063058589	mozrunner::runner	INFO	Running command: "/Applications/Firefox.app/Contents/MacOS/firefox-bin" "-marionette" "-profile" "/var/folders/99/kx9d7lpx7s5258rq49tpgs1s56bn5m/T/rust_mozprofile.6UAv09vwlbvm"
1521063058591	geckodriver::marionette	TRACE	  connection attempt 0/600
1521063058693	geckodriver::marionette	TRACE	  connection attempt 1/600
1521063058796	geckodriver::marionette	TRACE	  connection attempt 2/600
1521063058902	geckodriver::marionette	TRACE	  connection attempt 3/600
1521063058956	Marionette	DEBUG	Received observer notification "profile-after-change"
1521063059007	geckodriver::marionette	TRACE	  connection attempt 4/600
1521063059058	Marionette	DEBUG	Received observer notification "command-line-startup"
1521063059060	Marionette	INFO	Enabled via --marionette
1521063059111	geckodriver::marionette	TRACE	  connection attempt 5/600
1521063059216	geckodriver::marionette	TRACE	  connection attempt 6/600
1521063059323	geckodriver::marionette	TRACE	  connection attempt 7/600
1521063059426	geckodriver::marionette	TRACE	  connection attempt 8/600
1521063059528	geckodriver::marionette	TRACE	  connection attempt 9/600
1521063059630	geckodriver::marionette	TRACE	  connection attempt 10/600
1521063059736	geckodriver::marionette	TRACE	  connection attempt 11/600
1521063059842	geckodriver::marionette	TRACE	  connection attempt 12/600
2018-03-14 16:30:59.911 plugin-container[37698:7494343] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x14e3f, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
1521063059943	geckodriver::marionette	TRACE	  connection attempt 13/600
1521063060047	geckodriver::marionette	TRACE	  connection attempt 14/600
1521063060088	Marionette	DEBUG	Received observer notification "sessionstore-windows-restored"
1521063060153	geckodriver::marionette	TRACE	  connection attempt 15/600
1521063060258	geckodriver::marionette	TRACE	  connection attempt 16/600
1521063060282	Marionette	DEBUG	Setting recommended pref browser.newtabpage.enabled to false
1521063060282	Marionette	DEBUG	Setting recommended pref browser.newtabpage.introShown to true
1521063060282	Marionette	DEBUG	Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1521063060282	Marionette	DEBUG	Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1521063060282	Marionette	DEBUG	New connections are accepted
1521063060282	Marionette	INFO	Listening on port 56665
1521063060361	geckodriver::marionette	DEBUG	Connected to Marionette on localhost:56665
1521063060362	Marionette	DEBUG	Accepted connection 0 from 127.0.0.1:56706
1521063060363	geckodriver::marionette	TRACE	<- {"applicationType":"gecko","marionetteProtocol":3}
1521063060363	geckodriver::marionette	TRACE	-> 163:[0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1521063060364	Marionette	TRACE	0 -> [0,1,"newSession",{"acceptInsecureCerts":true,"browserName":"firefox","capabilities":{"desiredCapabilities":{"acceptInsecureCerts":true,"browserName":"firefox"}}}]
1521063060364	Marionette	WARN	TLS certificate errors will be ignored for this session
1521063060418	Marionette	DEBUG	Register listener.js for window 2147483649
1521063060422	Marionette	TRACE	0 <- [1,1,null,{"sessionId":"422c4306-cf6e-3347-8d65-5c1e3608d897","capabilities":{"browserName":"firefox","browserVersion":"59.0" ... 258rq49tpgs1s56bn5m/T/rust_mozprofile.6UAv09vwlbvm","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1521063060423	geckodriver::marionette	TRACE	<- [1,1,null,{"sessionId":"422c4306-cf6e-3347-8d65-5c1e3608d897","capabilities":{"browserName":"firefox","browserVersion":"59.0","platformName":"darwin","platformVersion":"17.4.0","pageLoadStrategy":"normal","acceptInsecureCerts":true,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000},"rotatable":false,"moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":37694,"moz:profile":"/var/folders/99/kx9d7lpx7s5258rq49tpgs1s56bn5m/T/rust_mozprofile.6UAv09vwlbvm","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
1521063060423	webdriver::server	DEBUG	<- 200 OK {"value": {"sessionId":"422c4306-cf6e-3347-8d65-5c1e3608d897","capabilities":{"acceptInsecureCerts":true,"browserName":"firefox","browserVersion":"59.0","moz:accessibilityChecks":false,"moz:headless":false,"moz:processID":37694,"moz:profile":"/var/folders/99/kx9d7lpx7s5258rq49tpgs1s56bn5m/T/rust_mozprofile.6UAv09vwlbvm","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"darwin","platformVersion":"17.4.0","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
Mar 14, 2018 4:31:00 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
1521063060469	webdriver::server	DEBUG	-> POST /session/422c4306-cf6e-3347-8d65-5c1e3608d897/url {"url":"https:www.google.com"}
1521063060469	geckodriver::marionette	TRACE	-> 42:[0,2,"get",{"url":"https:www.google.com"}]
1521063060470	Marionette	TRACE	0 -> [0,2,"get",{"url":"https:www.google.com"}]
1521063060478	Marionette	DEBUG	Received DOM event beforeunload for about:blank
1521063060804	Marionette	DEBUG	Received DOM event pagehide for about:blank
2018-03-14 16:31:00.855 plugin-container[37701:7494457] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0xad3f, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
1521063060934	Marionette	DEBUG	Received DOM event DOMContentLoaded for https://www.google.com/
1521063061594	Marionette	DEBUG	Received DOM event pageshow for https://www.google.com/
1521063061596	Marionette	TRACE	0 <- [1,2,null,{}]
1521063061597	geckodriver::marionette	TRACE	<- [1,2,null,{}]
1521063061597	webdriver::server	DEBUG	<- 200 OK {"value": {}}
1521063070107	webdriver::server	DEBUG	-> DELETE /session/422c4306-cf6e-3347-8d65-5c1e3608d897 
1521063070107	geckodriver::marionette	TRACE	-> 37:[0,3,"quit",{"flags":["eForceQuit"]}]
1521063070108	Marionette	TRACE	0 -> [0,3,"quit",{"flags":["eForceQuit"]}]
1521063070108	Marionette	DEBUG	New connections will no longer be accepted
1521063070150	Marionette	TRACE	0 <- [1,3,null,{"cause":"shutdown"}]
1521063070162	geckodriver::marionette	TRACE	<- [1,3,null,{"cause":"shutdown"}]
1521063070162	webdriver::server	DEBUG	Deleting session
1521063070162	geckodriver::marionette	TRACE	-> 37:[0,4,"quit",{"flags":["eForceQuit"]}]
1521063070170	Marionette	TRACE	0 -> [0,4,"quit",{"flags":["eForceQuit"]}]
1521063070170	Marionette	TRACE	0 <- [1,4,{"error":"invalid session id","message":"","stacktrace":"WebDriverError@chrome://marionette/content/error.js:172:5\nInva ... et@chrome://marionette/content/server.js:505:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:500:9\n"},null]
1521063070171	geckodriver::marionette	TRACE	<- [1,4,{"error":"invalid session id","message":"","stacktrace":"WebDriverError@chrome://marionette/content/error.js:172:5\nInvalidSessionIDError@chrome://marionette/content/error.js:327:5\nassert.that/<@chrome://marionette/content/assert.js:407:13\nassert.session@chrome://marionette/content/assert.js:81:3\ndespatch@chrome://marionette/content/server.js:554:7\nexecute@chrome://marionette/content/server.js:531:11\nonPacket/<@chrome://marionette/content/server.js:506:15\nonPacket@chrome://marionette/content/server.js:505:8\n_onJSONObjectReady/<@chrome://marionette/content/transport.js:500:9\n"},null]
1521063070178	Marionette	DEBUG	Closed connection 0
*** UTM:SVC TimerManager:registerTimer called after profile-before-change notification. Ignoring timer registration for id: telemetry_modules_ping
1521063070270	Marionette	DEBUG	Received observer notification "xpcom-shutdown"
1521063070270	Marionette	DEBUG	Resetting recommended pref browser.newtabpage.enabled
1521063070270	Marionette	DEBUG	Resetting recommended pref browser.newtabpage.introShown
1521063070272	Marionette	DEBUG	Resetting recommended pref toolkit.cosmeticAnimations.enabled
1521063070272	Marionette	DEBUG	Resetting recommended pref datareporting.policy.dataSubmissionPolicyAccepted
1521063070585	geckodriver::marionette	ERROR	Failed to stop browser process
1521063070603	webdriver::server	DEBUG	<- 200 OK {"value": {}}

**Comment by schmidtkp** [comment]
@andreastt Some more information... I started my local hub/node outside of IntelliJ and I get the same result, same trace-level log info. I also tried with Selenium v3.8.1, as well with latest v3.11.0 with same results. I also rebooted the MBP prior to all this to ensure I didn't have any locked ports or orphaned GeckoDriver process running.

I got the following info back as part of the remote stack trace when I attempted to run the tests:
```
remote stacktrace: stack backtrace:
   0:        0x10d5a949e - backtrace::backtrace::trace::h3ab5720c483fe461
   1:        0x10d5a94dc - backtrace::capture::Backtrace::new::h096accf58447e0d5
   2:        0x10d4e23e5 - webdriver::error::WebDriverError::new::hb28209cec8791fc2
   3:        0x10d4e35c5 - geckodriver::marionette::MarionetteHandler::create_connection::h59a68c8dfef48e54
   4:        0x10d4c8d3c - _$LT$webdriver..server..Dispatcher$LT$T$C$$u20$U$GT$$GT$::run::h5a26ba0bb4fdb139
   5:        0x10d4a10c5 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3f868f7a1a12bdcc
   6:        0x10d4abd2d - std::panicking::try::do_call::hfce1ad2a948c3632
   7:        0x10d655a5c - __rust_maybe_catch_panic
   8:        0x10d4beeb5 - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h651dedb755194a8c
   9:        0x10d651c4b - std::sys::imp::thread::Thread::new::thread_start::h48c72bb09587cbc3
  10:     0x7fff79ee86c0 - _pthread_body
  11:     0x7fff79ee856c - _pthread_start
```
Not sure what this is.

**Comment by schmidtkp** [comment]
@andreastt Please ignore my 2 previous comments, totally my error. I had updated my Firefox browser from v58.0.2 to v59.0 but _forgot_ to update my node configuration.

That said, I would swear (pre-v3.8.x?) that when you had a miss-match like this we use to get a very specific exception message saying something like "Browser version detected doesn't match requested...", making it very obvious what the issue was. Note to self...

**Comment by andreastt** [comment]
I’m not sure what problem you’re actually describing now. I can’t see a `session not created` error in your attached trace-log, and in your last comment you talk about a version mismatch. Can you supply a trace-log from an actual session where you have this problem?

**Comment by schmidtkp** [comment]
@andreastt As I mentioned in my previous comment, please ignore what I specifically wrote. It was user error on my part. I cannot speak for @chakravarthy who filed the original issue.

**Comment by whimboo** [comment]
Ok, closing issue given that original reporter didn't came back with more information so far.

**Comment by sirinibin** [comment]
Selenium 3.4.0 now recommends Geckodriver v0.16.0 strongly.
Refer this:
https://stackoverflow.com/questions/45510338/selenium-webdriver-3-4-0-geckodriver-0-18-0-firefox-which-combination-w
