### ISSUE TITLE
Element <input type="file"> is not reachable by keyboard

### ISSUE THREAD

**Issue by AlexanderArendar** [mozilla/geckodriver#1184]
## System

* Version: geckodriver 0.19.1
* Platform: Ubuntu Linux
* Firefox: 58.0 64 Bit
* Selenium: selenium-java 3.9.1

## Test case
This line of code
`find(xpath("//div[@class='form-group' and label[text()='Logo']]//input[@type='file']")).get.sendKeys(url.getPath)`

result in following exception:

```
1519129455174	geckodriver	INFO	geckodriver 0.19.1
1519129455179	geckodriver	INFO	Listening on 127.0.0.1:12785
1519129455488	mozrunner::runner	INFO	Running command: "/usr/lib/firefox/firefox" "-marionette" "-profile" "/tmp/rust_mozprofile.2WUD91A7yS8z"
1519129456219	Marionette	INFO	Enabled via --marionette
1519129457444	Marionette	INFO	Listening on port 46297
1519129457504	Marionette	WARN	TLS certificate errors will be ignored for this session
Feb 20, 2018 2:24:17 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C

Element <input type="file"> is not reachable by keyboard
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:25:02.294Z'
System info: host: 'POSITRON', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-112-generic', java.version: '1.8.0_161'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 58.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 18725, moz:profile: /tmp/rust_mozprofile.2WUD91..., moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 4.4.0-112-generic, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: 7d9c50dd-e24b-45a9-9da7-3c3f2ab1a722
org.openqa.selenium.ElementNotInteractableException: Element <input type="file"> is not reachable by keyboard
Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:25:02.294Z'
System info: host: 'POSITRON', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-112-generic', java.version: '1.8.0_161'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 58.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 18725, moz:profile: /tmp/rust_mozprofile.2WUD91..., moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 4.4.0-112-generic, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
Session ID: 7d9c50dd-e24b-45a9-9da7-3c3f2ab1a722
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:160)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:279)
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:100)
```
Please also note that the same test run on chromedriver works as expected.

## Trace Log
Attached as file
[trace.log](https://github.com/mozilla/geckodriver/files/1740065/trace.log)

**Comment by thejuskrishna** [comment]
same issue

**Comment by andreastt** [comment]
The error “Element <input type="file"> is not reachable by keyboard” means exactly what it says. The element can’t be reached using the keyboard, which means you can’t physically interact with it. Perhaps it’s hidden?

**Comment by andreastt** [comment]
FWIW this may be related to https://github.com/mozilla/geckodriver/issues/1173 if you’re using a JS framework that hides the form control.

**Comment by AlexanderArendar** [comment]
@andreastt , excuse me very much, but you just brutally closed the issue. 
If you took care to read everything I've described you would notice that the same code run with chromedriver functions ok.
So instead of guessing and closing, the better developer would take care, analyze attached trace log and tried to resolve the problem. Because I paid attention and time to compose this issue and provide you the log.

**Comment by AlexanderArendar** [comment]
@andreastt , thanks. I think it is indeed related to #1173.

**Comment by andreastt** [comment]
Also sprach AlexanderArendar:

> excuse me very much, but you just brutally closed the issue.  If
> you took care to read everything I've described you would notice
> that the same code run with chromedriver functions ok.
> 
> So instead of guessing and closing, the better developer would take
> care, analyze attached trace log and tried to resolve the problem.
> Because I paid attention and time to compose this issue and provide
> you the log.

You haven’t provided a reproducible test case, which is why I am
only guessing that it is related to
https://github.com/mozilla/geckodriver/issues/1173.  If it is the
case that your <input type=file> is obscured by another element/out
of view (e.g. has a CSS rule `display: none`), then that issue
matches the bill.

The bigger question being discussed on that issue is if it is the
correct behaviour for WebDriver to disallow interaction with hidden
file upload controls, given that modern JS frameworks use forms of
indirection to display a prettier UX.

It is currently the correct behaviour according to the WebDriver
standard to return an error whenever _any_ element is not
keyboard-interactable, so in light of this the Chrome behaviour is
not conforming to the specification.  However, I’d be most willing
to continue the discussion on an issue filed against the specification.

**Comment by AlexanderArendar** [comment]
Thanks for reply. I understand that you are bound to specification. And also understand that it could take months to decide wether the specification should be changed.

**Comment by hfontanez1968** [comment]
This is also failing for me with the latest Firefox driver and I can also confirm that this is working with Chrome.

In my case, I am trying to use an input element to upload picture. Interacting with this component, in my opinion, is the correct approach. Why? Because this will allow for a platform-independent solution. Otherwise, interacting with the visible "browse" button will open a "File Explorer" window that is platform-specific.

In my specific case, I am required to implement automated testing solutions that will work with all major browsers. Uploading photos is a major function of the services we provide and this issue is blocking my progress.  Lastly, I attempted a JS solution that was recommended on another site, and that doesn't work either due to a JS unsecure process exception (or something close to that).

**Comment by whimboo** [comment]
With the hopefully soon upcoming geckodriver 0.24 release in combination with Firefox 65 you will be able to use the `strictFileInteractability` capability to turn off the interactability checks for hidden `input` elements of type `file`. 

Details why this has been added can be found at: https://www.w3.org/2018/10/26-webdriver-minutes.html#item06.

**Comment by hfontanez1968** [comment]
Thank you very much for sharing this with me. I look forward to this new release. In the meantime, I will flag all my automated test cases that require this functionality as “Chrome-only” while the rest are tested on all browsers.

Once again, thank you.

Regards,
Hector
