### ISSUE TITLE
Gecko 0.18.0  musl lib up-gradation to latest version 

### ISSUE THREAD

**Issue by barahate90** [mozilla/geckodriver#1308]
## System

* Version: 0.18.0
* Platform: ubuntu bionic
* Firefox: 60
* Selenium: 3.4.0

Gecko driver is having one critical vulnerability in musl library and I want to update the musl  library to latest version 1.19.* for Gecko 0.18.0 

can you please help me with steps to rebuild the gecko from source code and where to exactly configure the musl lib. ?

**Comment by andreastt** [comment]
FYI the latest version of geckodriver is 0.21.0 so you should check if the problem is still prevalant there. We build against the latest musl available in Ubuntu.

Build instructions are found in the README:
https://github.com/mozilla/geckodriver#building

The canonical source code repository is mozilla-central, where geckodriver can be found under testing/geckodriver.

**Comment by whimboo** [comment]
@andreastt on Travis we use a `ubuntu:15.10` docker image, which is way outdated for building geckodriver! So no recent security fix will be available there because update sources simply don't work anymore.

If we publish from those Travis builds we should make it our P1 to upgrade to the latest Ubuntu for building geckodriver.

**Comment by andreastt** [comment]
I think time would be better invested enabling geckodriver to be built from TaskCluster. Working on a stop gap fix for something that will eventually be replaced seems like double work.

**Comment by whimboo** [comment]
I disagree here given that building geckodriver in TaskCluster is not an easy job and we should not ship vulnerable software. I created https://github.com/mozilla/geckodriver/pull/1311 to see if we can upgrade to the latest Ubuntu LTS release.

**Comment by barahate90** [comment]
@andreastt  vulnerability gets resolved when I upgraded the version to 0.19.0, But script execution is facing issue with 0.19.0 version. my script works best with 0.18.0  gecko version. So looking forward to understanding the way to build the project by upgrading the musl lib latest.

I agree with @whimboo  shipping the vulnerable software is not a good practice. So if you can try to build the gecko 0.18.0 with latest musl lib that will solve the issue.

**Comment by whimboo** [comment]
@barahate90 we will not rebuilt 0.18.0 given that this version is no longer supported. As said earlier try to always make use of the latest release of geckodriver. If executing scripts has a problem you should file a new issue with all the details included.

So far it looks like this issue is not actionable anymore and can be closed.
