### ISSUE TITLE
Cargo.lock file is missing

### ISSUE THREAD

**Issue by jelly** [mozilla/geckodriver#1403]
Please add a cargo.lock file to geckodriver to make it possible to have reproducible geckodriver builds.

## System

* Version: 0.23.0
* Platform: Linux
* Firefox: 62.0.3
* Selenium: 3.14.1

**Comment by andreastt** [comment]
We do have a Cargo.lock file here: https://searchfox.org/mozilla-central/source/Cargo.lock#961

**Comment by whimboo** [comment]
I think we should make it clear that building geckodriver should be done via the mozilla-central checkout, and not via the mirrored code here on the Github repository.

**Comment by andreastt** [comment]
Fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1500938.

**Comment by das-g** [comment]
Does https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Releasing.html need updating, too? It links to https://searchfox.org/mozilla-central/source/testing/geckodriver/Cargo.lock, which now gives a 404 error.

**Comment by whimboo** [comment]
Yes, that page needs an update. I wanted to cover that via https://bugzilla.mozilla.org/show_bug.cgi?id=1504144.

The building docs can be found here:
https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Building.html

**Comment by whimboo** [comment]
Over on issue #1427 it was brought up how to easily identify the changeset a geckodriver release was built from. I would agree that we should add a tag to the changelog right beside the version which helps people to easily checkout the appropriate changeset to build geckodriver on their own.

Landing wise it is tricky because we don't know the commit id beforehand. As such an update to the changelog would have to be landed as follow-up commit with just `r=docs` set in the commit message. @andreastt what's your take here?

**Comment by andreastt** [comment]
> I would agree that we should add a tag to the changelog right beside the version which helps people to easily checkout the appropriate changeset to build geckodriver on their own.

Isn’t this identified in `--version`?

**Comment by whimboo** [comment]
First, you would have to download a geckodriver build, to check that. But secondly `--version` doesn't give any commit id. Probably it fails because we release from github, and only tested that the commit id is present in m-c. 

Alternative solution for the commit id could be the table at https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Support.html.

**Comment by andreastt** [comment]
It’s unfortunate that Mercurial doesn’t support tagging, because synchronising the release (the bumping of the version number in testing/geckodriver/Cargo.toml) with the hg SHA is near impossible, as well as very labour intensive.

There is a recursive problem here if you want the changelog to contain the version number of the release commit, because you don’t know the SHA of the commit you’re about to make before after it has been committed.  This means the changelog can only be updated post-the-fact with the SHA used to make the commit. Amending the commit is similarly no use, because the SHA changes when the patch’s content changes. A further complication is git-cinnabar, where you have to also convert from git to hg.

But if we are fine with the changelog being updated with the release SHA _after_ the release has been made, I have no objections.

**Comment by das-g** [comment]
A two-step lookup (i.e. see tip of branch x for tags or pointers to specific revisions for each release) is fine with me.

Though, I gotta wonder: How do you guys (or, for that matter, packagers / package maintainers for other Linux distributions) currently look up the source of past releases? I kinda doubt I'm the first one wanting to do that.

**Comment by eli-schwartz** [comment]
https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/firefox#n24

We checkout https://hg.mozilla.org/mozilla-unified using a magic reference to `tag=FIREFOX_${pkgver//./_}_RELEASE` (so, `tag=FIREFOX_63_0_3_RELEASE`) which then uses `hg update -C -r FIREFOX_63_0_3_RELEASE`.

In firefox 52.0.1 we switched to this, where previously we preferred using the tarballs, because apparently telemetry only works when building directly from mercurial.

**Comment by eli-schwartz** [comment]
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/geckodriver

**Comment by whimboo** [comment]
Then I would really suggest that we add this information to https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Support.html. That would avoid the post-release modification of the CHANGES.md file.

If you agree I'm happy to update that file to reflect it for all the last releases.

**Comment by whimboo** [comment]
@andreastt can you please check my last comment? Do we want to do it that way?

**Comment by andreastt** [comment]
I think we should keep the (hg) commit SHA in the changelog. That’s where I would look for it.

**Comment by whimboo** [comment]
Starting with the 0.24.0 release of geckodriver the changelog will be part of the CHANGES.md file.

See: https://hg.mozilla.org/integration/autoland/rev/a9a40a96a2fe

The release will be out later today or tomorrow.
