### ISSUE TITLE
Unknown field 'sessionId, expected one of Implicit, 'pageload', 'script' at line 1 column 12 in GECKODRIVER 0.23.0 linux version?

### ISSUE THREAD

**Issue by agrawalsmart7** [mozilla/geckodriver#1422]
As I have posted the error in question can anyone have any idea about whats going on?

Can anyone please help me in there. 

Note:- Before I use 0.14.0 version but that version also shows error i.e. message timeouts So I decided to install latest version.

**Comment by andreastt** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html

**Comment by whimboo** [comment]
Not sure which Selenium binding you are using, but it clearly adds an additional `sessionId` property to the payload of the `timeouts` command:

> webdriver::server DEBUG -> POST /session/c62819b7-2ebf-43a2-96c7-12981a1fd3aa/timeouts {"pageLoad": 20000, "sessionId": "c62819b7-2ebf-43a2-96c7-12981a1fd3aa"}

Please file an issue against the Selenium binding if that problem is still persistent. It's not a geckodriver issue.

**Comment by agrawalsmart7** [comment]
okay thanks for guiding me.

**Comment by whimboo** [comment]
@andreastt I wonder if we should relax the deserialization in geckodriver a bit and simply ignore those extra and unknown properties. The spec is not that clear at this point (https://w3c.github.io/webdriver/#dfn-parsing-as-json), and might allow us to do so.

**Comment by andreastt** [comment]
The problem here is the second step in the remote end steps for [Set Timeouts](https://w3c.github.io/webdriver/#dfn-timeouts) which says to iterate over each enumerable own property in the parameters field. When a field is not in the [table of session timeouts](https://w3c.github.io/webdriver/#dfn-table-of-session-timeouts) that causes a problem because it isn’t recognised.

The remainder of the WebDriver specification is written in such a way that any extra JSON data is ignored. This effect is achieved by explicitly reading the necessary data and ignoring other fields. I feel the spec should be changed to allow for this in Set Timeouts too.

**Comment by whimboo** [comment]
@andreastt will you file a webdriver specification issue for that?

**Comment by whimboo** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1507782 covers the Marionette, and maybe also geckodriver changes.

**Comment by whimboo** [comment]
Should have been already fixed years ago in Firefox 66.
