### ISSUE TITLE
Gecko driver issue v 0.23 with downloading open H264.

### ISSUE THREAD

**Issue by AMANDUA** [mozilla/geckodriver#1423]
## System

* Version: 0.23.0
* Platform: both mac 10.13 and windows 10
* Firefox: 63
* Selenium: 3.14

## Description

we are using webdriver and nodejs binding to run automation.
Also we are using webrtc to make video calls which requires open H264,
Till firefox version 62 and gecko driver 0.20.1 there was no issue , but now with firefox version 63 and gecko driver version 0.23.0 there is isssue in downloading open H264 plugin.

Seems to be a issue with gecko driver version 0.23.0

Could you please have a look into the issue.

**Comment by whimboo** [comment]
It's by design. By default the preference `media.gmp-manager.updateEnabled` is disabled. This is because only a small amount of people actually have to test pages with those plugins enabled, and downloading those each time causes extra costs.

If you need the media plugins just setup your profile in Selenium that this preference is set to `true`.

**Comment by AMANDUA** [comment]
Thanks @whimboo
