### ISSUE TITLE
Input type attribute returning incorrect values

### ISSUE THREAD

**Issue by titusfortner** [mozilla/geckodriver#1469]
"datetime-local" type elements are returning type attribute values of "text"

```
<label for="html5_datetime-local">HTML5 Datetime Local</label>
<input type="datetime-local" id="html5_datetime-local" name="html5_datetime-local" />
```

```
irb(main):032:0> driver = Selenium::WebDriver.for :firefox
=> #<Selenium::WebDriver::Firefox::Marionette::Driver:0x43a12d9e09a5e28e browser=:firefox>
irb(main):033:0> driver.get "http://watir.com/examples/forms_with_input_elements.html"
irb(main):034:0> element = driver.find_element(id: 'html5_datetime-local')
=> #<Selenium::WebDriver::Element:0x6662c64acc15e42c id="9d123ae8-080d-2843-99d3-0ee1d67d710f">
irb(main):036:0> element.attribute('type')
=> "text"
irb(main):037:0> 
```

**Comment by titusfortner** [comment]
Oh, just found this related bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1424984

I guess I don't understand why "lacking support" means that it is ok to return the wrong attribute value.

**Comment by andreastt** [comment]
As you can see from https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local, `<input type=datetime-local>` isn’t supported in Firefox. The relevant bug here is https://bugzilla.mozilla.org/show_bug.cgi?id=888320.

Since this is a Firefox issue and not a geckodriver issue, I’m going to close this as I don’t think any action needs to be taken in either geckodriver or Marionette once the underlying Gecko bug is resolved.
