### ISSUE TITLE
set_window_size fails if horizontal window size ==  horizontal screen resolution.

### ISSUE THREAD

**Issue by mehmetg** [mozilla/geckodriver#153]
**Settings:**
**Screen Resolution:** 1280 x 1024
**Requested browser window size:** 1280x 1024 (1280x 1023 works)
**OS:** Windows 10
**GeckoDriver:** ? (Running on Sauce Labs, so not sure.)
**Browser:** FF 47.0.1

It works on MacOS 10.11 not on windows 10

**Comment by andreastt** [comment]
Are you sure you are using geckodriver and Marionette? I was not aware Sauce Labs had support for this yet.

**Comment by mehmetg** [comment]
@andreastt They just started supporting it. `{"marionette":"true"}` desired capability enables it. 
I'll try to repro locally today. TBH I do not know which entity is throwing the exception. Se or geckodriver

**Comment by andreastt** [comment]
Please make sure you use the most recent Firefox Nightly when you try to reproduce. I recently [removed a check in _Set Window Size_](https://bugzilla.mozilla.org/show_bug.cgi?id=1280101) which could affect this.

You also didn’t say what fails or what input was given.

You need to be aware that requesting a window size does not necessarily _give_ you the requested window size because operating system level UI elements may obscure parts of the screen. So for example if the screen resolution is 1280x1024 and the bottom 10x1280 pixels of the screen is used for the start panel, requesting window size 1280x1024 will return 1280x1014.

**Comment by mehmetg** [comment]
I'll try to repro soon and update. 
I am OK with the window size not being exact, I can always read back and check, but the fact that Se server exits with an error makes it a problem. I'll do an @-mention when I have more info.

**Comment by mehmetg** [comment]
@andreastt: I have just tested it out using with Se beta 3 using geckodriver 0.10.0 and FF48.
Oddly enough vertical sizing works as expected by ignoring anything beyond what's possible and the horizontal sizing cannot do => (active) screen resolution.

**Comment by AutomatedTester** [comment]
I have just tried to recreate this issue and couldn't. I have added a test to Marionette to make sure we dont regress it. see https://reviewboard.mozilla.org/r/138568
