### ISSUE TITLE
Robot framework issue: Unable to find a matching set of capabilities

### ISSUE THREAD

**Issue by venukalakota** [mozilla/geckodriver#1534]
I am new to Robot framework and need your help to fix the below issue:

I have below in my PyCharm:

*** Settings ***
Documentation  This is a basic test
Library  SeleniumLibrary

*** Variables ***

*** Test Cases ***
User must sign in to check out
    [Documentation]  This is a basic test
    [Tags]  Smoke
    Open Browser  https://www.amazon.com chrome
    sleep  3s
    close browser

*** Keywords ***

Then Ran the case and got the below fail:

SessionNotCreatedException: Message: Unable to find a matching set of capabilities

Any help to fix this is highly appriciated

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

Most likely geckodriver cannot find the Firefox binary. So make sure it is located at the default location on your disk, or explicitly specify it in the Robot framework.

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html

**Comment by venukalakota** [comment]
There are no logs found in the gecodriver.log, not sure what is happening?

**Comment by whimboo** [comment]
Maybe run it outside of PyCharm? Without the log we cannot help, and you might better contact the folks of the robot framework.

**Comment by venukalakota** [comment]
@qa-trainee 

Added the details mention in point, but still getting the error:

*** Settings ***
Documentation  This is a basic test
Library  SeleniumLibrary
Library  OperatingSystem

*** Variables ***


*** Test Cases ***

User must sign in to check out
    [Documentation]  This is a basic test
    [Tags]  Smoke
    Set Environment Variable webdriver.chrome.driver C:/bin/chromedriver.exe
    Open Browser  https://www.amazon.com chrome
    sleep  3s
    close browser

Please suggest

**Comment by qa-trainee** [comment]
You have to follow point number 1 too and use exact lines from point number 4.

Ie download chromedriver.exe and save it in c:\bin 

Add c:\bin to your path variable in environment variables. 

And then use exact code from point number 4

**Comment by whimboo** [comment]
Closing issue given that it is not geckodriver related.

**Comment by DvaKompota** [comment]
I know that this ticket is not really related to geckodriver, as @venukalakota had "chrome" instead of "firefox" in his Test Case

But this is the first link on the search request `robotframework firefox SessionNotCreatedException: Message: Unable to find a matching set of capabilities`, so I'll post a solution, that worked for me when I had a similar problem.

My system: 
Version: geckodriver : 0.24.0-**win32**
Platform: Windows 10
Firefox: 68.0.2 (**64-bit**)
python                                    3.7.4
robotframework                     3.1.2
robotframework-seleniumlibrary  3.3.1
PyCharm 2019.2 (CE)

I guess you already see the root of the problem: the Firefox browser was originally installed with the 64-bit version, while geckodriver I used for the project was for some strange reason 32-bit.
So just replacing it with a 64-bit version solved my problem

**Comment by whimboo** [comment]
For reference I described the issue @DvaKompota was having at https://github.com/mozilla/geckodriver/issues/1168#issuecomment-521932079.
