### ISSUE TITLE
GeckoDriver eats lots of memory

### ISSUE THREAD

**Issue by KOLANICH** [mozilla/geckodriver#1587]
## System

* Version: 0.24.0
* Platform: Windows 7
* Firefox: 69.0b5
* Selenium: 4.0.0a1

More than a 10 MiB for a service utility is IMHO too much. But it eats ~1.5 GiB.

**Comment by andreastt** [comment]
This isn’t a hugely actionable bug, but please help me understand what exactly is using memory. geckodriver spawns Firefox as a subprocess, which again has many more subprocesses due to its multiprocessing architecture.

We have a known memory leak in Firefox when using WebDriver, tracked in https://github.com/mozilla/geckodriver/issues/181, but it’s unclear to me from this bug if it’s the parent geckodriver process that eats memory or the Firefox subprocess?

**Comment by KOLANICH** [comment]
The pattern is following:
* first `python` starts eating memory.
* then geckodriver eats it, python frees it
* then firefox is spawned and most of memory consumed by geckodriver is freed.

I have not verified that, but a very naive guess that compression and decompression of profile dir is done in memory before dumping it to disk rather than doing it in streamed fashion chunk by chunk.

**Comment by andreastt** [comment]
If the Python client process is consuming the most amount of memory, that is a bug in the client library and not in geckodriver.

**Comment by KOLANICH** [comment]
@anreast, again
* python eats
* python frees, geckodriver eats (more than python had eaten)
* firefox starts, geckodriver frees

I have not dug into the sources of selenium, but I know a copy of profile is made. Though I am not sure that profile is the cause because my profile folder is not that big.

**Comment by whimboo** [comment]
@KOLANICH first try without a custom profile. Just let geckodriver create it. Further you want to use a memory tracking tool to somewhat upload a trace of the memory usage of all the affected processes. The information here is so far not actionable for us.
