### ISSUE TITLE
WebDriverManager-versioned 3.6.1 (Gecko driver versioned 0.24.0) Problem - Firefox versioned 68.0.1 64 bit , Windows 10 , Selenium version 3.141.59

### ISSUE THREAD

**Issue by arsekisser** [mozilla/geckodriver#1594]
## System

* Version:  **geckodriver version 0.24.0**
* Platform:  **Windows Version 10.0.10240 Build 10240** 
* Firefox:  **68.0.1** 
* Selenium:  **3.141.59** version  

I am Using **WebDriverManager**-**versioned 3.6.1** (Gecko driver versioned 0.24.0) Problem - Firefox versioned 68.0.1 64 bit , Windows 10 , Selenium version 3.141.59

## Issue

 
Hi ,
I have a maven -selenium project with 10+ test classes in testNG.

When i execute these classes on Chrome browsers(WebDriverManager-chrome driver) ,each test class gets executed successfully .
Same test classes when i execute on Firefox using the (WebDriverManager-Gecko driver) the test classes execute for some time say 5-10 seconds and then abruptly closes and opens next test class for execution ,even this test class execute for some time and then closes . 
Same thing happens with each test class.

Suggest some work around for executing the test classes on Firefox browser successfully .
 

## Stacktrace

 
[Just log.docx](https://github.com/mozilla/geckodriver/files/3434363/Just.log.docx)

**Comment by andreastt** [comment]
This is not an actionable bug report. Can you please be more specific about what your problem is?

Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html

**Comment by arsekisser** [comment]
The problem is when i use WebDriverManager(Gecko driver) for running automation on Firefox , the test run abruptly crashes withing 20-30 seconds and starts to execute next test case .Same thing happens with each test case.

While same thing when we run on chrome executes successfully

**Comment by whimboo** [comment]
This seems to happen because of:

> 2019-07-26 10:47:27 INFO  Dashboard.java:173  - Exception occured : org.openqa.selenium.WebDriverException: TypeError: can't access dead object

Sadly the above isn't a [trace log](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html), so not sure which specific command fails here. As such please attach another log file (but please not as doc but txt). Also some code would be great to have.

**Comment by whimboo** [comment]
No response from the reporter. I'm happy to reopen if the requested trace log can be provided.
