### ISSUE TITLE
can't kill an exited process

### ISSUE THREAD

**Issue by shweta8996** [mozilla/geckodriver#1600]
## System

* Version: 
* Platform: 
* Firefox: 
* Selenium: 

what is the fix for this issue? i have same problem. i have tried all different combination of the geckodriver, firefox selenium

geckodriver 0.24.0
firefox 62.0.02
selenium 3.14

i still see the error cant kill an exited process. same thing works well on local machine its failing only when i push the docker in gitlab and run it there

from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.firefox.options import Options

def before_all(context):
    # Taking input of browser name from behave.ini file and selecting the browser .
    browser_name = str.lower(context.config.userdata['browser'])

    # Selecting Firefox browser on input firefox/FIREFOX/Firefox/F/f
    if browser_name == 'firefox' or browser_name == 'f':
        try:
            #options = webdriver.FirefoxOptions()
            #options.add_argument('-headless')
            geckodriver = '/usr/local/bin/geckodriver'

            options = Options()
            options.add_argument('-headless')

            # options = Options()
            # options.headless = True
            caps = DesiredCapabilities().FIREFOX.copy()
            caps["pageLoadStrategy"] = "none"
            context._the_browser = webdriver.Firefox(executable_path=geckodriver, capabilities=caps, options=options)
            context._the_browser.implicitly_wait(10)
        except Exception as e:
            print('Error while initializing the ', browser_name, ' :--', e)

## Trace-level log

Checking out 2b1405a4 as SP/read_and_inject_quantum_js_file_test...
Removing automated_tests/features/steps/__pycache__/
Removing automated_tests/geckodriver.log
Removing quantum.js

Skipping Git submodules setup
Downloading artifacts for build (16838)...
Downloading artifacts from coordinator... ok        id=16838 responseStatus=200 OK token=RVdsKgxX
$ ./bdd_gitlab.sh
Error while initializing the  firefox  :-- Message: invalid argument: can't kill an exited process

**Comment by shweta8996** [comment]
here is my docker file that i am using

FROM ubuntu:18.04

# Install dependencies
RUN apt-get update && apt-get install -y \
    software-properties-common
RUN add-apt-repository universe
RUN apt-get update && apt-get install -y \
    sudo \
    curl \
    netcat \
    git \
    wget \
    unzip \
    python3.5 \
    python3-pip && pip3

#=========
# Firefox
#=========
#RUN curl https://ftp.mozilla.org/pub/firefox/releases/59.0.2/linux-x86_64/en-US/firefox-59.0.2.tar.bz2  > firefox-59.0.2.tar.bz2 \
#    && tar -xvjf firefox-59.0.2.tar.bz2 \
#    && rm firefox-59.0.2.tar.bz2 \
#    && mv firefox /opt/firefox59
#RUN ln -sf /opt/firefox59/firefox /usr/bin/firefox

ARG FIREFOX_VERSION=62.0.2
RUN wget --no-verbose -O /tmp/firefox.tar.bz2 https://download-installer.cdn.mozilla.net/pub/firefox/releases/$FIREFOX_VERSION/linux-x86_64/en-US/firefox-$FIREFOX_VERSION.tar.bz2 \
   && rm -rf /opt/firefox \
   && tar -C /opt -xjf /tmp/firefox.tar.bz2 \
   && rm /tmp/firefox.tar.bz2 \
   && mv /opt/firefox /opt/firefox-$FIREFOX_VERSION \
   && ln -fs /opt/firefox-$FIREFOX_VERSION/firefox /usr/bin/firefox

#============
# GeckoDriver
#============
RUN curl -L https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz \
        > geckodriver-v0.24.0-linux64.tar.gz \
    && tar -xzf geckodriver-v0.24.0-linux64.tar.gz \
    && rm geckodriver-v0.24.0-linux64.tar.gz \
    && mv geckodriver /usr/local/bin \
    && chmod -R 777 /usr/local/bin



#ARG GECKODRIVER_VERSION=vgeckodriver-v0.23.0-linux64.tar.gz
#RUN curl -L https://github.com/mozilla/geckodriver/releases/download/v0.23.0/$GECKODRIVER_VERSION \
#        > $GECKODRIVER_VERSION \
#    && tar -xzf $GECKODRIVER_VERSION \
#    && rm $GECKODRIVER_VERSION \
#    && mv geckodriver /usr/local/bin

#=========
# Chrome
#=========
#RUN curl https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o /chrome.deb
#RUN sudo dpkg -i /chrome.deb || sudo apt-get install -yf
#RUN rm /chrome.deb

#=============
# Chromedriver
#=============
#RUN wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
#RUN unzip chromedriver_linux64.zip
#RUN sudo mv chromedriver /usr/bin/chromedriver
#RUN sudo chown root:root /usr/bin/chromedriver
#RUN sudo chmod +x /usr/bin/chromedriver

RUN pip3 install selenium==3.14.0  && rm -rf /root/.cache
RUN pip3 install behave            && rm -rf /root/.cache

RUN sudo apt-get update && apt-get install -y \
        xvfb \
        libfontconfig \
        libxrender1 \
        libxcomposite1 \
        libasound2 \
        libgtk2.0-0 \
        uuid-runtime \
    && rm -rf /var/lib/apt/lists/* /var/log/* /usr/share/man/* /usr/share/doc/*

WORKDIR /src

**Comment by dsmh** [comment]
I'm running into the same problem, but with a silighty diferent combination:

System: Raspbery Pi 3
Version: 0.23.0 
Platform: ARM
Firefox: 60.8.0

I also have tried all different combination of the geckodriver and firefox 

**This is the traceback from selenium with geckodriver 0.23:**
 
`Traceback (most recent call last):
  File "automation_test.py", line 15, in <module>
    driver = Firefox(executable_path='geckodriver', options=options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process`

**This is the geckodriver.log:**
`1565549491856	mozrunner::runner	INFO	Running command: "/usr/bin/firefox" "-marionette" "-headless" "-foreground" "-no-remote" "-profile" "/tmp/rust_mozprofile.fTWQY8SbCcdR"
*** You are running in headless mode.
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
ExceptionHandler::GenerateDump cloned child 2116
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
` 
This was with geckodriver 0.23, however on another forums they recomend to work with the version 0.17. With this downgrade the errors were diferent. 

**This is the traceback from selenium with geckodirver 0.17**
`Traceback (most recent call last):
  File "automation_test.py", line 15, in <module>
    driver = Firefox(executable_path='geckodriver', options=options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused`

**This is the geckodriver.log with version 0.17**

`1565550045169	geckodriver	INFO	Listening on 127.0.0.1:58555
1565550046783	geckodriver::marionette	INFO	Starting browser /usr/bin/firefox with args ["-marionette", "-headless"]
*** You are running in headless mode.
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
JavaScript error: resource://gre/modules/XPCOMUtils.jsm, line 187: TypeError: undefined has no properties
ExceptionHandler::GenerateDump cloned child 2216
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
Unable to init server: Could not connect: Connection refused`

I'm kind of lost now, how can I make to work my code?

**BTW, the code I'm trying to run is this:** 

`from selenium.webdriver import Firefox
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.support import expected_conditions as expected
from selenium.webdriver.support.wait import WebDriverWait
#from pyvirtualdisplay import Display


if __name__ == "__main__":
    #display = Display(visible=0, size=(800, 600))
    #display.start()
    options = Options()
    options.add_argument('-headless')
    driver = Firefox(executable_path='geckodriver', options=options)
    wait = WebDriverWait(driver, timeout=5)
    driver.get('http://www.google.com')
    wait.until(expected.visibility_of_element_located((By.NAME, 'q'))).send_keys('WiF ID' + Keys.ENTER)
    wait.until(expected.visibility_of_element_located((By.CSS_SELECTOR, '#ires a'))).click()
    print(driver.page_source)
    driver.quit()`

The commented lines were a test since another solution posted was to configure the display, but I had not luck with that either

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html

**Comment by dsmh** [comment]
> Could you please attach a [trace-level log](https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html) from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines](https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/Bugs.html).

Hi, both links gave me a 404 error, so I could not see the contribution guidelines, let me know if the trace-level-log is the same I can see on geckodriver.log, if so, I already added them on my last post.

**Comment by whimboo** [comment]
Sorry, but the documentation location got updated. Also the above logs aren't trace logs. Here the links again:

Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by whimboo** [comment]
No further feedback from reporter. Closing the issue.
