### ISSUE TITLE
Files are not downloaded automatically

### ISSUE THREAD

**Issue by raczeja** [mozilla/geckodriver#1707]
## System

* Version: 0.26.0.1
* Platform: Windows 10
* Firefox: 
* Selenium: 74.0.1  64

## Testcase

<a href="download/some-file.txt">some-file.txt</a>
https://the-internet.herokuapp.com/download 

Files are not downloaded automatically, event following options are set for profil:
https://github.com/ObjectivityLtd/Ocaramba/blob/master/OcarambaLite/DriverContext.cs#L212

 `// preference for downloading files
ptions.SetPreference("browser.download.dir", this.DownloadFolder);
options.SetPreference("browser.download.folderList", 2);
options.SetPreference("browser.download.managershowWhenStarting", false);
 options.SetPreference("browser.helperApps.neverAsk.saveToDisk", "application/vnd.ms-excel, application/x-msexcel, application/pdf, text/csv, text/html, application/octet-stream");

// disable Firefoxs built-in PDF viewer
 options.SetPreference("pdfjs.disabled", true);

// disable Adobe Acrobat PDF preview plugin
options.SetPreference("plugin.scan.Acrobat", "99.0");
options.SetPreference("plugin.scan.plid.all", false);`

It used to work.

**Comment by whimboo** [comment]
Could you please attach a [trace-level log] from geckodriver? Read more about reporting actionable bugs in our [contribution guidelines].

Also the text file is inappropriately served with a content type of `application/octet-stream` instead of `text/plain`. Any reason for this wrong content type?

[trace-level log]: https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html
[contribution guidelines]: https://firefox-source-docs.mozilla.org/testing/geckodriver/Bugs.html

**Comment by raczeja** [comment]
please find attached logs
[file.log](https://github.com/mozilla/geckodriver/files/4450128/file.log)
[downloads.txt](https://github.com/mozilla/geckodriver/files/4450130/downloads.txt)

regarding this 

> Also the text file is inappropriately served with a content type of application/octet-stream instead of text/plain. Any reason for this wrong content type?

I don't know, it used to work, It's still working with the e.g. Firefox 63 and newest GeckoDriver

**Comment by raczeja** [comment]
issue cause by policy PromptForDownloadLocation = true, can be check in Firefox "about:policies#active"

**Comment by whimboo** [comment]
Thanks!
