### ISSUE TITLE
How to set device screen size?

### ISSUE THREAD

**Issue by dkuchynskyi** [mozilla/geckodriver#1747]
## System

* Version: v0.26.0
* Platform: Windows 10
* Firefox: 78.0.2
* Selenium: python v.3.141.0

I am trying to emulate mobile devices by setting preference "general.useragent.override".
But I can't figure out how set device screen size.
Could you please help?
Thanks

**Comment by whimboo** [comment]
Device emulation is not possible with webdriver because it's not part of the [WebDriver specification](https://w3c.github.io/webdriver) yet. It will be added for [WebDriver BiDi](https://w3c.github.io/webdriver-bidi) though within the next couple of months. 

As such there is nothing we can do right now. Sorry.
