### ISSUE TITLE
0.27.0 metadata

### ISSUE THREAD

**Issue by bollwyvl** [mozilla/geckodriver#1753]
Hi folks, congratulations on the release!

I know it's only been 11 hours, but looking for a few things for downstream packaging:
- what is the minimum firefox?
  - not appearing yet in [the docs](https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html)
- what is the canonical hg commit?
  - some of the dependency crates don't appear to be published, so still having to build from source
  - a naive search has lead me to 
    - `09dbca8803460053ac9a3b89d9e049065df1c963`
  - which when downloading `{commit}.zip/testing` has a sha256 of
    - `c2078f3d529c88288bc0856f23bc53e9a5fce88136c529e99c7bc10872891f62`

Any other gotchas on this release?

**Comment by jgraham** [comment]
The minimum Firefox is unchanged from 0.26; I'll make sure that gets updated.

The canonical commit is in the GitHub repo, https://github.com/mozilla/geckodriver/blob/release/CHANGES.md#0270--2020-07-27-90ec81285ff6 I think we want to move to a system where we only publish it there in the future because having to add it to the gecko source tree creates unnecessary extra work.

The crate publishing problem is known; there is an issue there we need to fix. Apologies for the delay.

**Comment by bollwyvl** [comment]
Thank you!

**Comment by whimboo** [comment]
I assume the meta data issue has been clarified now. The build problem we also track on issue #1695.
