### ISSUE TITLE
Selenium Ruby issue with geckodriver - Selenium::WebDriver::Error::ElementNotVisibleError: for elements that are visible according to the DOM

### ISSUE THREAD

**Issue by danqa** [mozilla/geckodriver#179]
I have a modal window that opens in my web page. The modal is long so you have to scroll to the bottom of it. When that happens part of the modal  (the top) is hidden to the user as its above the top fold of the browser window. When this happens and selenium wants to access an element that is in that part of he modal you get:

```
Selenium::WebDriver::Error::ElementNotVisibleError:
       Element is not visible
```

The element is not hidden according to the DOM yet selenium cannot see it. This is new behavior with geckodriver as the firefox driver could interactive with this type of element. Is this now intended behavior? It seems that it should not be if the element is not hidden according to the DOM.

**Comment by andreastt** [comment]
Currently Marionette uses the same visibility algorithm atom as Selenium and FirefoxDriver, so this is a little surprising. The intention is to move to the WebDriver specification definition of [pointer-interactability](http://w3c.github.io/webdriver/webdriver-spec.html#dfn-pointer-interactable-element) in the future. You can try this new behaviour now by setting the `specificationLevel` capability to `1`. It would be interesting to see if that acts differently.

I’m assuming the error you describe above happens when you try to interact with the element, e.g. click it. Is this the case?

The future definition of whether an element is _interactable_ will be if the centre point of the first DOM element rectangle is inside the viewport or not.

**Comment by AutomatedTester** [comment]
As Andreas points out we are using the code from the Selenium project. Without steps to reproduce (which include a script and HTML) there isnt much we can do.

**Comment by danqa** [comment]
Hi there. Sorry I have not responded sooner but was out of the country the last 10 days. @andreastt You are correct that the issue happens when I try to interact with an element that is now not in the viewport. What happens it the modal is larger that the window. I click a button that generates an error (expected behavior) but the modal moved down to show that error. Now the element I want to interact with is not in viewport. When I run this on firefox 47 it works fine. On version 48 is is now giving the error above. @AutomatedTester I cannot provide an example as this is happening in a part of the system that I cannot provide outside access to. I will see if I can create a reproducible script for you to see what is occurring.

**Comment by danqa** [comment]
Haven't been able to create a script yet but wanted to give more context. As I said this issue is with a modal window that pops-up in our system. This issue does not occur on the main browser window. So for example, if I do window.scrollTo(0,500) the main window scrolls down. If I do this when the modal is open the main window scrolls in the background the the modal doesn't move. I suspect this is why selenium view the element. This is what is different from firefoxDriver to geckodriver that would cause this issue now. I'll continue to see if I can generate an example script.
