### ISSUE TITLE
OSError: [Errno 86] Bad CPU type in executable: ver/v0.29.1/macos/geckodriver]

### ISSUE THREAD

**Issue by ValeriiIavtushenko** [mozilla/geckodriver#1867]
## System

* Version: 
* Platform: 
* Firefox: 
* Selenium:

**Comment by whimboo** [comment]
For everyone who notice that please make sure that there are two binaries of geckodriver now that can be downloaded. So if you are using a script you most likely scrape for the wrong binary type.

**Comment by ValeriiIavtushenko** [comment]
exactly( I just renamed old 0.29.0 to 0.29.1 for now - cose im learning Selenium WebDriver
Thanks anyway

**Comment by KartarC** [comment]
Still having a hard time trying to fix this error on my Mac Catalina (version 10.15.6). It was working fine since last night and the error popped up this morning. There are 2 versions, version 0.29.1 & version 0.30.0. any help? 

OSError: [Errno 86] Bad CPU type in executable: '/Users/kartarC/InstaPy/assets/geckodriver'
