### ISSUE TITLE
[Android] "EOF reading marionette message" error at attempt to start new session

### ISSUE THREAD

**Issue by a-en** [mozilla/geckodriver#1893]
## System

* Version: 0.29.1
* Platform: Mac OS X 10.15.4 
* Firefox: 88.1.4 and 89.0.0-beta.10

## Testcase

1. Start geckodriver 
2. Try to create session by sending the request to localhost (POST to http://localhost:4444/session)

```
{
  "capabilities": {
    "alwaysMatch": {
      "moz:firefoxOptions": {
        "androidPackage": "org.mozilla.firefox_beta",
        "androidDeviceSerial": "emulator-5554",
        "log": {"level": "trace"}
      }
    }
  }
}
```

## Stacktrace

```
{
    "value": {
        "error": "timeout",
        "message": "Socket timeout reading Marionette handshake data: EOF reading marionette message",
        "stacktrace": ""
    }
}
```

## Trace-level log

[geckodriver.log](https://github.com/mozilla/geckodriver/files/6569963/geckodriver.log)

**Comment by whimboo** [comment]
@a-en would you mind to enable [Trace Logs](https://firefox-source-docs.mozilla.org/testing/geckodriver/TraceLogs.html), and sharing an excerpt from `adb logcat` around the time when geckodriver waits for the Marionette reply? Thanks a lot.

**Comment by a-en** [comment]
@whimboo, correct me if I'm wrong, but one of the option to enable Trace logs is to provide `"log": {"level": "trace"}` in the capabilities (which I've put in the list of caps in this case)
Please take a look on the [adb.log](https://github.com/mozilla/geckodriver/files/6571044/adb.log)

**Comment by whimboo** [comment]
Thank you for the adb log! It clearly shows that there is a hang during the startup of Firefox on Android. Searching for `Marionette` reveals only these two lines:

```
05-31 17:50:12.918  8568  8603 I Gecko   : 1622472612918	Marionette	INFO	Marionette enabled
05-31 17:50:13.329  8568  8603 I Gecko   : 1622472613329	Marionette	TRACE	Received observer notification toplevel-window-ready
```

Next we should receive `Received observer notification marionette-startup-requested` but that never happens. Which version of Firefox is it exactly that is failing here? I'm fairly sure it's a release earlier than 90.0 and as such will require the `devtools.debugger.remote-enabled` preference to be set to `true`. This is a known problem, and got fixed in Firefox 90. Also see our Android specific `known issues` section of the recent geckodriver release notes:

https://github.com/mozilla/geckodriver/releases/tag/v0.29.1

As such try with Firefox 90beta on Android, and if that still not works please reopen the issue.

**Comment by a-en** [comment]
@whimboo, thanks for you comment!
I've mentioned Firefox versions which had this issue in original description, you are right, they are lower than 90.0 (88.1.4 and 89.0.0-beta.10).
As for devtools.debugger.remote-enabled -- I saw this in release notes and tried, but haven't realized that it should be wrapped in `prefs`
So now with updated caps everything works fine:

```
{
  "capabilities": {
    "alwaysMatch": {
      "moz:firefoxOptions": {
        "androidPackage": "org.mozilla.firefox",
        "androidDeviceSerial": "emulator-5554",
        "log": {"level": "trace"},
        "prefs": {
            "devtools.debugger.remote-enabled": true
        }
      }
    }
  }
}
```
Thanks @whimboo for assistance in resolving this!

**Comment by whimboo** [comment]
Sounds great! So please don't forget to remove it once Firefox 90 has been released. Otherwise you will also have running the debugger server of DevTools.
