### ISSUE TITLE
BLOCKING ISSUE - Naming Convention

### ISSUE THREAD

**Issue by jonniespratley** [mozilla/geckodriver#193]
Hello, on versions prior to geckodriver-v0.10.0-macos.tar.gz you spell the mac driver as `geckodriver-vx.x.x-mac.tar.gz` but 0.10.0 is spelled `macos.tar.gz` Which is failing our build servers, we are trying to release something and really need your help on renaming this to match the others. 

WCT is the one who is trying to fetch `mac.tar.gz` but it does not exist.

**Comment by stephenash** [comment]
Tools like [selenium-standalone](https://github.com/vvo/selenium-standalone) are also impacted by this. See https://github.com/vvo/selenium-standalone/issues/207

**Comment by jonniespratley** [comment]
Whats the ETA on this fix? Seems easy if a new release is uploaded with a updated name.

**Comment by ckedwards** [comment]
This naming scheme seems to unexpectedly change. I know your drivers aren't technically at 1.0.0 yet, but please don't needlessly antagonize the developers.

It looks like recently the naming scheme has changed, sometimes arbitrarily, every release. Can we just agree to never change the naming scheme again for sanity's sake?

v0.10.0
geckodriver-v0.10.0-macos.tar.gz

v0.9.0
geckodriver-v0.9.0-**mac**.tar.gz

v0.8.0
geckodriver-0.8.0-**OSX**.gz

v0.7.1
**wires**-0.7.1-OSX.gz

v0.6.0
wires-0.6.0-**osx**.gz

**Comment by andreastt** [comment]
The naming of the packages changed in 0.10.0 as part of our work towards releasing from Travis instead of it being a manual process. The work involved happened mostly in https://github.com/mozilla/geckodriver/commit/54a96438a7d7a5c8da51f082aff300ac22dc1a4d and https://github.com/mozilla/geckodriver/commit/567e2f5b160fbe85e185f50b4ea7b3a5e9fe23e7.

The platform names that 0.10.0 were released with will stay consistent from here on.

It’s also worth adding that Apple renamed their operating system between 0.9.0 and 0.10.0, from Mac OS X to macOS with a versioning number.
