### ISSUE TITLE
Geckodriver 30.0 fails to locate certain kinds of page elements correctly.

### ISSUE THREAD

**Issue by chrismcmahon** [mozilla/geckodriver#1954]
## System

* Version: 30.0
* Platform: Mac and Windows at least
* Firefox: 93.0
* Selenium: 4.0 Ruby client

## Testcase

<img width="480" alt="Screen Shot 2021-11-05 at 12 11 13 PM" src="https://user-images.githubusercontent.com/204643/140812678-9c38e08b-747f-49a8-a675-255915f81129.png">

My app has a "donut" chart with shaped "slices" as shown in the attached screen shot. For many past versions of Selenium and geckodriver I have been able to address at least three of these slices of this donut chart. After updating to Selenium 4.0 and geckodriver 30.0, my tests get an unusual error.

In particular, hovering over one of those svg elements with the <g> tag should change the value in the center of the donut. Before Se4 I was able to address at least 3 of those <g> elements. Since upgrading to Se4, the code that used to work now reports errors such as `(485, -28) is out of bounds of viewport width (1280) and height (865) (Selenium::WebDriver::Error::MoveTargetOutOfBoundsError)` . Different elements have different w/h values, (464, -23) and (500, -30) and on a different donut on the same page (not shown in the screenshot) (1109, -7)

At first I thought the error was with Selenium, but I discussed the issue with Selenium contributor Titus Fortner who believes that the issue is with geckodriver. 

## Stacktrace

(1109, -7) is out of bounds of viewport width (1280) and height (865) (Selenium::WebDriver::Error::MoveTargetOutOfBoundsError)
      WebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:181:5
      MoveTargetOutOfBoundsError@chrome://remote/content/shared/webdriver/Errors.jsm:371:5
      dispatchPointerMove/<@chrome://remote/content/marionette/action.js:1383:13
      dispatchPointerMove@chrome://remote/content/marionette/action.js:1374:10
      toEvents/<@chrome://remote/content/marionette/action.js:1145:16
      action.dispatchTickActions@chrome://remote/content/marionette/action.js:1055:35
      action.dispatch/chainEvents<@chrome://remote/content/marionette/action.js:1023:20
      action.dispatch@chrome://remote/content/marionette/action.js:1029:5
      performActions@chrome://remote/content/marionette/actors/MarionetteCommandsChild.jsm:447:18
      receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.jsm:141:31

**Comment by chrismcmahon** [comment]
Thanks for the reply! 
 I updated to Selenium4 and geckodriver30 simultaneously and found this issue. I am not sure that I can revert either of them easily. 

A full trace log is attached. 

One more piece of information: I am locating this element with the <g> tag by way of its :class attribute. My original script would hover over the child of the element, but I checked both, and I get the "out of bounds of viewport width" error for both the element and the child of the element.  The element is clearly in the viewport area and always has been. 
[donut_slice_locate_failure_trace_log.txt](https://github.com/mozilla/geckodriver/files/7506481/donut_slice_locate_failure_trace_log.txt)

**Comment by whimboo** [comment]
The attached log is from Selenium and doesn't contain any logging from geckodriver nor Marionette. I don't know how the Ruby binding is working, but maybe check if there is a separate geckodriver.log file around.

Do you have the code in a repository? Maybe you could checkout a version that still uses Selenium 3.x and a former release of geckodriver. Then just replace the binary. Or what's broken with Selenium 4 when you use geckodriver 0.29.1?

**Comment by chrismcmahon** [comment]
Sorry about the log! I misunderstood the settings.  This log is large but does contain the geckodriver information. 
[big_log.txt](https://github.com/mozilla/geckodriver/files/7506835/big_log.txt)

**Comment by whimboo** [comment]
Strange. So in line 52 of the lag I can see the last debug line of Marionette. Then Selenium somehow(?) starts geckodriver again (line 62), which launches another instance of Firefox that uses a different Firefox profile and doesn't have the trace logging preference set. As such the logs as given are still not helpful. :/

But the action as triggered seems to be:
```
2021-11-09 10:27:47 INFO Selenium    >>> http://127.0.0.1:4481/session/156d6c2d-0dde-b140-9807-71ac0b3bf2ff/actions | {"actions":[{"type":"pointer","id":"mouse","actions":[{"type":"pointerMove","duration":250,"x":0,"y":0,"origin":{"element-6066-11e4-a52e-4f735466cecf":"da8790da-8e5a-604d-abd2-615c5b17a9b0"}}],"parameters":{"pointerType":"mouse"}}]}
```

As such I wonder why it tries to move the element to `(487, -28)` (see the negative number) which is clearly outside of the viewport that is (0, 0, 1280, 865).

**Comment by whimboo** [comment]
Ah and interestingly the only place where we make use of the [`move target out of bounds` error message is in atom.js](https://searchfox.org/mozilla-central/search?q=move+target+out+of+bound&path=remote%2Fmarionette).

The file was moved internally in June (without modifying any contained code), and [last updated in 2020](https://hg.mozilla.org/mozilla-central/log/1b1cf5db66257b31fd2dab40de9b033d6fb60a17/testing/marionette/atom.js).

As such the failure should indeed come from Selenium itself because it submits these huge Atom blobs on its own. I think this is something special that the Ruby bindings are doing. @titusfortner should be able to help here. And I strongly believe the atoms got updated between the 3.x and 4.x release, which now are causing trouble.

**Comment by chrismcmahon** [comment]
This is very helpful, thank you! I'll follow up with Titus

**Comment by titusfortner** [comment]
@chrismcmahon yeah, you are starting Firefox twice in your example here.

So, the only atoms that Selenium sends are for `isDisplayed` and `getAttribute`, so changes in `atom.js` shouldn't be the issue from the bindings. I believe that atom is still getting copied from Selenium by Mozilla? How often is that done?

That said, one thing that is different is that ,since Actions class does not automatically scroll element into view, Watir added an automatic JS scroll (`arguments[0].scrollIntoView();`) Maybe this is moving the element out of bounds for you? We have a PR to address this actually and allow you more control over where it scrolls: https://github.com/watir/watir/pull/949

Let me do a merge/release and you can see if that fixes it. I'm not sure why it's showing as negative values in the return, though.

**Comment by whimboo** [comment]
That's interesting in regards of `scrollIntoView()`. Maybe there was a change in Firefox that might have triggered the over-scrolling so that parts of the element are outside of the visible viewport now? @chrismcmahon did you also test with an older release of Firefox? 

Is that graphic actually an SVG? Also is this page publicly accessible, or could you provide a minimized HTML/SVG testcase for it? I don't see why `scrollIntoView()` with the default setting of `top` would overscroll here. Thanks.

**Comment by chrismcmahon** [comment]
Yes, this has been working in older versions of Firefox/Geckodriver/Selenium/Watir for a long time. However, note that these "donut slice" elements, unlike almost every other kind of web page element, are not symmetrical on the horizontal or vertical axes. This could be a factor in the strange over-scrolling. Selenium for example calculates the "center" of the element, which in the case of these slices means that a click() or hover() action may actually land outside some of these more curved elements, and the element does not respond. 

This page is not publicly available unfortunately, and the underlying code has been heavily modified. However, if you search for "vue donut" you can find a number of similar examples that are more simple.

**Comment by whimboo** [comment]
> That said, one thing that is different is that ,since Actions class does not automatically scroll element into view, Watir added an automatic JS scroll (`arguments[0].scrollIntoView();`) Maybe this is moving the element out of bounds for you? We have a PR to address this actually and allow you more control over where it scrolls: [watir/watir#949](https://github.com/watir/watir/pull/949)
> 
> Let me do a merge/release and you can see if that fixes it. I'm not sure why it's showing as negative values in the return, though.

@chrismcmahon did this actually help?

**Comment by titusfortner** [comment]
Yes, we got it working for him.

**Comment by whimboo** [comment]
That's great to hear. In this case lets close this issue.
