### ISSUE TITLE
"crypto.randomUUID() is not a function" error on a blank tab when running Firefox with geckodriver

### ISSUE THREAD

**Issue by IlyaHarlamov** [mozilla/geckodriver#2116]
## System

* Version: 0.33.0
* Platform: Windows 10
* Firefox: 102.11.0esr

## Testcase
crypto.randomUUUID function is not available when running Firefox 102.11.0esr with geckodriver (reproduced with 0.31.0 and 0.33.0). When trying to call the crypto.randomUUUID function from the browser console, an error "crypto.randomUUID is not a function" is returned.
The function is available in the browser when running the browser manually without geckodriver.

**Comment by whimboo** [comment]
This is actually not related to geckodriver but an issue in Firefox. geckodriver just sets the preference `browser.startup.page` to `0` so that only a single tab is open with `about:blank` loaded. And as it looks like this page doesn't allow to use this API.

When I start Firefox normally and set the settings under `New Windows and Tabs` both to `Blank Tab`, I can access the API when opening a new tab. But once I explicitly load `about:blank` in that newly created tab the API is not available anymore. 

@smaug---- do you have an idea why that is the case? If it's a bug I'm happy to file it but not sure where exactly right now.

**Comment by whimboo** [comment]
Note that whenever a real page is loaded the API is available. It's just the blank page which causes the issue.

**Comment by IlyaHarlamov** [comment]
Hmm, I am using Selenide to run the tests, when I open a real page with it, the issue is still there... Not sure how this preference works, or maybe there is any other preference affecting this. I guess something to investigate a bit more

**Comment by IlyaHarlamov** [comment]
Ok, more information: the "real page" I am opening is hosted on the localhost. For instance, when I open google.com, the API is available, but on the localhost it is not.

**Comment by smaug----** [comment]
blank page isn't secure context, and randomUUID() is available on secure contexts only.
See [SecureContext] annotation in https://w3c.github.io/webcrypto/#crypto-interface

**Comment by whimboo** [comment]
Thanks @smaug---- ! Looks like we can close this issue then.
