### ISSUE TITLE
Update broken link in README

### ISSUE THREAD

**Issue by shailshouryya** [mozilla/geckodriver#2148]
The https://github.com/mozilla/geckodriver/blob/79cef6e77f250228e4463d3dedac54b9d9369c17/README.md?plain=1#L34

link under the [Documentation section](../blob/master/README.md#documentation) from the [README](../blob/master/README.md) points to https://seleniumhq.github.io/docs/, which redirects to https://www.selenium.dev/docs/, which is currently a 404. However, https://www.selenium.dev/documentation/ does work, so I think `README.md` should be updated to

```diff
--- a/README.md
+++ b/README.md

@@ -33, +33

- [Selenium](https://seleniumhq.github.io/docs/) (work in progress)
+ [Selenium](https://www.selenium.dev/documentation/) (work in progress)
  * [C# API](https://seleniumhq.github.io/selenium/docs/api/dotnet/)
```

I also noticed the base domain seleniumhq.github.io redirects to www.selenium.dev - so should all other `https://seleniumhq.github.io/RESOURCE` links be updated to `https://www.selenium.dev/RESOURCE` as well?

I can also make a pull request here, but looking at [this comment](./2138#discussion_r1347034854) from a recent pull request, I'm not sure if that change would go here (on GitHub), or somewhere else?

**Comment by whimboo** [comment]
Thank you @shailshouryya! We might certainly update the readme regarding your proposals. If you want to make a contribution you are welcome and I can help to guide you through the process.

As you noticed we do not accept PRs on the GitHub repository because it's not the canonical one. Documentation in how to get started you can find at https://firefox-source-docs.mozilla.org/testing/geckodriver/index.html. Feel free to also join our [Matrix channel](https://chat.mozilla.org/#/room/#webdriver:mozilla.org) for a direct communication. Thanks in advance!

**Comment by whimboo** [comment]
For now I've added a working item for our next 0.35.0 release of geckodriver:
https://bugzilla.mozilla.org/show_bug.cgi?id=1871543

**Comment by whimboo** [comment]
This is now fixed. Thanks again for reporting it!
