### ISSUE TITLE
BUG: geckodriver.exe is not working on Windows 7 environment. 

### ISSUE THREAD

**Issue by deadsqrl** [mozilla/geckodriver#2198]
## System

* Version: 0.35.0
* Platform: Windows 7 pro SP1
* Firefox: 115.15.0esr (32-bit)
* Selenium: 4.11.2

## Testcase

from selenium import webdriver
driver = webdriver.Firefox()

## Stacktrace

Traceback (most recent call last):
  File "C:\Python37\error.py", line 2, in <module>
    driver = webdriver.Firefox()
  File "C:\Python37\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 60, in __init__
    self.service.start()
  File "C:\Python37\lib\site-packages\selenium\webdriver\common\service.py", line 109, in start
    self.assert_process_still_running()
  File "C:\Python37\lib\site-packages\selenium\webdriver\common\service.py", line 122, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service C:\Users\Adm\.cache\selenium\geckodriver\win64\0.35.0\geckodriver.exe unexpectedly exited. Status code was: 3221225785 

## Issue source
 Essentially even when i try to simply run the geckodriver.exe through cmd, it show an error related to **bcryptprimitives.dll** .
![2024-09-17_173249](https://github.com/user-attachments/assets/64c40310-6b54-44a7-b64c-0e83f1a43922)

**Comment by whimboo** [comment]
The latest geckodriver binary is built with Rust 1.80.0. And since version 1.78 Windows 7 is no longer supported. See the release notes appropriately: https://blog.rust-lang.org/2024/05/02/Rust-1.78.0.html#compatibility-notes

You could use an older version of geckodriver if you don't need the newest features, or you can try to build geckodriver yourself by installing Rust and Cargo first and running `cargo install geckodriver`.

Not sure if we can / want to go back to a Rust release like 1.77.2 to build geckodriver. CC @jgraham.

**Comment by whimboo** [comment]
Alternatively please check if that library file is present on your system. Maybe it was accidentally deleted or quarantined?

**Comment by deadsqrl** [comment]
The file is presented in system32 folder, but is different from one on windows 10.
If i place win10 version of dll to the folder with driver it asks for another dll.
![image](https://github.com/user-attachments/assets/0f66e1d0-27a0-4430-b8d7-e8ece93981e5)
Now it askes for **api-ms-win-core-libraryloader-l1-2-0.dll** i assume it keeps asking for more stuff...
Yes we could use previous version just fine, but i was worrying that in future releases of firefox older drivers become incompatible, and thus unusable.
So it is only solution to roll back rust version and build the driver manually for this case?

**Comment by jgraham** [comment]
Assuming the older version works I think that's the best solution. ESR115 isn't expected to change much at this point, so if it works once it should continue to do so.

**Comment by whimboo** [comment]
Please note that Firefox 115 ESR support will stop soon so we will also stop geckodriver to officially support this version. But as James said you can still use it as long as it works. Otherwise you still have the option to build yourself as long as older versions of Rust are able to compile the code. If that's no longer the case geckodriver 0.34.0 can still be used as long as you have to run this Windows 7 machine.

Based on that I'm going ahead and close this bug as wontfix.
