### ISSUE TITLE
Command line arguments to pass profile directory and proxy

### ISSUE THREAD

**Issue by aplicacionamedida** [mozilla/geckodriver#277]
The current implementation pass the profile directory as a base 64 encoded of this directory to the value of the key "profile" of the desired capabilities.

The proxy is passed using a similar approach. It's the value of the key "proxy" of the desired capabilities. This value is a dictionary of possible of proxies: httpProxy, ftpProxy, sslProxy,...

The browser arguments are passed also using desired capabilities. It's the value of the key "args".

It would be nice to add the possibility to pass more info to geckodriver using command line arguments. For example, path to profile directory, proxy settings or other browser arguments.

These are the current command line arguments:
```
    -b, --binary <BINARY>              Path to the Firefox binary
        --log <LEVEL>                      Set Gecko log level [values: fatal, error, warn, info, config, debug, trace]
        --marionette-port <PORT>    Port to use to connect to Gecko (default: random free port)
        --host <HOST>                     Host ip to use for WebDriver server (default: 127.0.0.1)
    -p, --port <PORT>                     Port to use for WebDriver server (default: 4444)
```

**Comment by andreastt** [comment]
The main way to configure geckodriver is on a session-by-session basis, by providing a set of capabilities when starting a new session. Normally it picks up the system installation of Firefox if `--binary` is not given, and you could imagine modifying the `PATH` environment variable to achieve the same effect.

E.g. the following are equivalent:

    % geckodriver -b /usr/local/firefox/firefox
    % PATH=/usr/local/firefox geckodriver

I feel the ability to set the binary through a flag is a bit weird since it acts as a fallback to finding the system installation. In fact I just patched the Selenium Python client last week not to use `--binary` and instead rely on geckodriver’s logic to fin the right Firefox.

I’m also sceptical that adding _more_ configuration options will qualitatively improve geckodriver. I suspect the opposite might be the case, that fewer ways to screw things up is better.

**Comment by aplicacionamedida** [comment]
It's a question of usability. If powerful options are provided, another linux users can use directly geckodriver like any other linux utility without the need of external code. This is my point of view.

**Comment by davehunt** [comment]
@aplicacionamedida there's no need for external code - if you're starting geckodriver and want it to launch a specific binary or profile, you just provide the necessary capabilities in your start session request. This can be done via Selenium or anything else that understands the WebDriver specification.

**Comment by jgraham** [comment]
Yes, this is an intentional decision at the moment. Where we previously had command line options users often didn't know how to set them from their choice of WebDriver client. However being able to set parameters to new session ("capabilities") is something that all users are familiar with. Adding multiple ways to set the same options only adds complexity.

In the future I would only consider adding command line options if there's a compelling use case that can't be addressed by capabilities alone.

**Comment by aplicacionamedida** [comment]
There is a use case that it's not possible with geckodriver. Suppose the situation that someone wants to start firefox hidden on windows. This feature is possible on Linux setting an environment variable DISPLAY and using Xvfb. On windows the only solution is to get a handle for the window, for example using the title, and then to call to the win32 API function "ShowWindow". Or using Autohotkey it's possible with the function "WinHide". But it's not possible on windows to start directly hidden firefox using geckodriver.
