### ISSUE TITLE
Plugins mess

### ISSUE THREAD

**Issue by ihatemozilla** [mozilla/geckodriver#282]
Geckodriver is a gd mess, Firefox used to be my reference for stable testing, not so much anymore.
rant /

Using selenium v3.0.0 with Java and latest firefox/geckodriver. My tests hang and console shows this:

`1476724946463	addons.productaddons	INFO	sending request to: https://aus5.mozilla.org/update/3/GMP/49.0.1/20160922113459/WINNT_x86-msvc-x64/en-US/release/Windows_NT%2010.0.0.0%20(x64)/default/default/update.xml
1476724946998	addons.productaddons	INFO	Completed downloading document
1476724947835	addons.productaddons	INFO	downloadXHR File download. status=200
1476724947839	addons.productaddons	INFO	Downloaded file will be saved to C:\Users\dndlab\AppData\Local\Temp\tmpaddon
1476724948968	addons.productaddons	INFO	downloadXHR File download. status=200
1476724948972	addons.productaddons	INFO	Downloaded file will be saved to C:\Users\dndlab\AppData\Local\Temp\tmpaddon
1476724949890	addons.productaddons	INFO	downloadXHR File download. status=200
1476724949893	addons.productaddons	INFO	Downloaded file will be saved to C:\Users\dndlab\AppData\Local\Temp\tmpaddon
JavaScript error: https://support.cdn.mozilla.net/static/build/common-min.80cc97d7f66d.js, line 10: Error: Error retrieving geoip data
JavaScript error: https://support.cdn.mozilla.net/static/build/common-min.80cc97d7f66d.js, line 10: Error: Error retrieving geoip data`

Looking online for support with those plugins and no luck. From what I understand, geckodriver is trying to download:
gmp-eme-adobe
gmp-gmpopenh264
gmp-widevinecdm

Any help for this?

Thanks

**Comment by jgraham** [comment]
Sorry, but this issue is totally unactionable. I have no idea what you're trying to do, or what geckodriver is doing in response.

I apologise for the instability around geckodriver. We were forced into making the release sooner than anticipated due to plugin signing, and have opted to frontload the migration pain by aiming for the W3C spec rather than trying to reverse-engineer the nonstandard behaviour of Selenium.

Before reporting further issues you may wish to consider whether your choice of username is motivating the humans behind this project to spend their time helping you, or encouraging them to work instead on one of the numerous other things that competes for their time.

**Comment by TJEvans** [comment]
I am encountering the same issue
FF Version: 49.0.2
GeckoDriver Version: 0.11.1

Hanging in a call to driver.get(https://www.google.com/#q=Pangolin)

**Comment by guohainan** [comment]
I was in trouble with the same problem with ghost.
@ghost Do you have any suggestions which can disable that?

**Comment by whimboo** [comment]
It's not GeckoDriver which is downloading those plugins but Firefox. If you don't want that you will have to tell it Firefox via some preferences. Therefore open `about:config` in Firefox and search for `gmp`. Each preference ending with `enabled` can be flipped, to prevent Firefox downloading the accociated plugin.
