### ISSUE TITLE
geckodriver not handling deferred or lazy loaded content

### ISSUE THREAD

**Issue by fspinillo** [mozilla/geckodriver#310]
## Current Behavior

When clicking .body or any other element, Firefox is not loading the deferred / lazy loaded content

## Expected Behavior

Clicking anywhere on the page should trigger this content to be loaded

## Steps to Reproduce

Below is a quick test to show deferred / lazy loaded content not loading on interaction. When the site detects a human interaction the remaining content is displayed. The sleep is not needed, but was added to allow time to see what I'm describing.

```
from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep

driver = webdriver.Firefox()
driver.get('http://vimeo.com/38138')
driver.find_element(By.CSS_SELECTOR, '.body_ribbon').click()
sleep(5)
driver.close()
```

To see this in a non Selenium scenario do the following:
1. Open a private window
2. Go to http://vimeo.com/38138
3. Don't click or do anything after hitting submit

Observer how the page is showing throbbers / loaders while it waits for you to move your mouse or click somewhere
 
## Your Environment

selenium 3.0.1
48.0.1

## Comments

I think this is related to geckodriver as this was not an issue with the old webdriver. I checked to see if the same thing was happening in Chrome and it's not. Chrome is properly handling the click interaction and loading content.

**Comment by andreastt** [comment]
I suspect this is because chromedriver incorrectly waits for the element (`.body_ribbon`) to become visible before performing the click. This is what is known as an implicit wait for an element to become interactable.

The [WebDriver specification](http://w3c.github.io/webdriver/webdriver-spec.html) says we shouldn’t do that, and so geckodriver doesn’t. You can work around this by employing an explicit wait before clicking.
