### ISSUE TITLE
Element scrolled into top of viewport rather than bottom

### ISSUE THREAD

**Issue by ChrisLMerrill** [mozilla/geckodriver#327]
On the Apache.org page, clicking the Ant links (located by link text "Ant") will scroll slightly past the element and then try to click on it. The click() call succeeds, but apparently does not actually happen, as Firefox does not follow the link.
The attached SSCCE demonstrates the problem.

[ApacheAntLinkFailsInMarionetteTest.java.txt](https://github.com/mozilla/geckodriver/files/582361/ApacheAntLinkFailsInMarionetteTest.java.txt)

**Comment by andreastt** [comment]
I’ve managed reproducing this, but it happens because there is a fixed overlay menu that follows the page as you scroll:

![screenshot-2016-11-14-165255](https://cloud.githubusercontent.com/assets/399120/20273910/e932a79c-aa8a-11e6-9e47-f4c36764277b.png)

So you’re right that Marionette does indeed scroll to the element, but the click that is issued ends up hitting the overlay that hides the “Ant” link.

**Comment by andreastt** [comment]
I think the specification’s definition of a [scrolled into view element](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-scrolled-into-view) is wrong, and I believe we had a previous action item that we needed to specify `scrollIntoView()`’s arguments.

If I recall correctly most driver implementations currently use `false`, which according to [CSSOM(https://drafts.csswg.org/cssom-view/#enumdef-scrolllogicalposition) equates to `{block: "end", inline: "nearest"}`, so I will file a PR against the WebDriver spec to address this.

This unfortunately does not address the fundamental problem, but it does solve perhaps the more common scenario where there is a fixed menu at the top. It’s rarer to see these at the bottom of the viewport.

**Comment by andreastt** [comment]
WebDriver PR: https://github.com/w3c/webdriver/pull/440

**Comment by andreastt** [comment]
Filed Marionette bug https://bugzilla.mozilla.org/show_bug.cgi?id=1317386.
