### ISSUE TITLE
Not able to execute following JavaScript

### ISSUE THREAD

**Issue by AshwinK1989** [mozilla/geckodriver#329]
Hi Team,
I am not  able to execute following JavaScript while running selenium tests on firefox. It returns null as a WebElement. However works well for the browsers      

` WebElement elementAtClick = (WebElement) executor(driver).executeScript("return document.elementFromPoint(" + clickX + ", " + clickY + ");");`

Hope the issue will be resolved asap.
Thank you.

**Comment by brianjoyner** [comment]
Reporting a similar situation.  

Using NodeJS bindings from webdriver.io:

```
describe('suite description', function (){
	it('test description', function(){
		page.openWebsite(testPath);
		var toReturn = browser.execute(function(){return window.scrollY;});
		console.log(toReturn.value);
       });
});
```

**Comment by AZWN** [comment]
Also experienced this issue with firefox 47.0.2 on windows 10, and geckodriver 0.11.1. 
This [stackoverflow answer](http://stackoverflow.com/questions/40179379/selenium-3-javascriptexecutor-returns-referenceerror) brought me a workaround, allthough I still would like to have this issue fixed, and have ExecuteScript behave the same as in other drivers.

**Comment by dthielman** [comment]
@AZWN great link.

Getting a similar problem with trying to set the value on a CodeMirror instance. It's solved by indexing into `wrappedJSObject`:

```
.execute(function(text) {
        document.querySelector(".CodeMirror").wrappedJSObject.CodeMirror.setValue(text)
      }, ['some text])
```

The above works, but is not (of course) safe across non-Gecko drivers. A cross-driver solution is easy enough, but makes the code a bit nasty. This was especially challenging to debug since executing JS in the browser console yields different results than the executed JS passed into the driver. 

Big fan of integration testing in FF, nonetheless.

**Comment by whimboo** [comment]
@AshwinK1989 it's been a while since the last comment on this issue, but I would like to know on which website you were experiencing this problem. Was it one driven by some kind of framework like React? Also does it still happen for you?

**Comment by whimboo** [comment]
Also a [trace log](https://firefox-source-docs.mozilla.org/testing/geckodriver/geckodriver/TraceLogs.html) would be kinda helpful.

**Comment by AshwinK1989** [comment]
@whimboo Not facing this issue anymore. so closing it.
