### ISSUE TITLE
Does Geckodriver support Windows XP 32-bit?

### ISSUE THREAD

**Issue by zhiying8710** [mozilla/geckodriver#392]
## Firefox Version
NaN

## Platform
Windows XP 32-bit
Geckodriver  version:  0.11.1

## Steps to reproduce -
I ran geckodriver in shell, then "ktmw32.dll not found" showed, does Geckodriver support Windows XP 32-bit?

**Comment by andreastt** [comment]
We do support 32-bit Windows, however we only support Windows XP with all the latest service packs. You should not be missing ktmw32.dll or any system DLLs.

I would point you towards https://social.msdn.microsoft.com/Forums/en-US/530ccab5-9c98-47d9-8435-31391975aee4/where-to-get-ktmw32h-and-ktmw32dll?forum=windowstransactionsprogramming or ask this question in a relevant Microsoft support channel.

Do note that Windows XP will stop working with Firefox 53, however. Since XP has numerous security issues, you are strongly advised to upgrade your operating system.

**Comment by andreastt** [comment]
Correction to my above answer: I’m being told ktmw32.dll was introduced in Windows Vista, so I guess we don’t support Windows XP with geckodriver.

Since Windows XP support in Firefox is being removed with Firefox 53, I don’t think we are going to jump through any hoops to get geckodriver working with XP. Again, my very strong suggestion is that you need to upgrade your operating system.

**Comment by omero72** [comment]
Wouldn't it be possible to build geckodriver without depending on ktmw32.dll ? And from which version on did geckodriver started to depend on it?

**Comment by andreastt** [comment]
It might be, but I don’t have the bandwidth to figure out how to with the mingw cross compilation chain. I suspect we depended on ktmw32.dll since we started releasing geckodriver for Windows, or possibly when we started cross-compiling it from Linux.

As always patches are welcome for this, but it is a hard-requirement that we continue to be able to build from CI for Windows. E.g. installing an ancient proprietary Visual Studio in a VM to compile it is not a good solution.
