### ISSUE TITLE
There is no CLI option to set the geckodriver log destination

### ISSUE THREAD

**Issue by barancev** [mozilla/geckodriver#415]
There is no CLI option to set the geckodriver log destination
(like /log-file in IEDriverServer or --log-path in chromedriver)

**Comment by andreastt** [comment]
You can redirect the log using `>`:

```
% ./geckodriver --v >geckodriver.log
```

**Comment by barancev** [comment]
Yes, we can do this, but it makes binding implementations non-generic -- most driver servers have an option to redirect the log to a file, but the geckodriver.

If you are strongly opposed introducing this option you can close the issue and move this responsibility to the binding implementers, of course :)

**Comment by andreastt** [comment]
I guess I’m failing to see a practical use case, apart from “other browsers do this”. If we supply this flag, it too will necessitate some change the consumer in order to start using it, and I don’t see the difference in redirecting the output stream to a file or adding another flag to the arguments calling geckodriver. If binding authors want to produce a log file from geckodriver, they don’t really need a flag to do so.

**Comment by barancev** [comment]
An ability to pass an option is already implemented (in Java binding al least). Without the option we'll have to implement output handling for geckodriver unlike it is already implemented for other driver servers.

I want to reiterate that is is possible, no doubt. But it makes bindings' code less homogeneous.

**Comment by andreastt** [comment]
Closing this because the output from the geckodriver program is not different from the output that would be produced if we had a flag for redirecting it (in some cases, for other programs, this is often the case), it does not seems like a high toll to expect consumers to capture the stdout + stderr.

I’m more sympathetic towards https://github.com/mozilla/geckodriver/issues/414, so I’m going to consider that more seriously. Ideally we would have a logging interface for getting server, driver, browser, and console logs, and not one-off driver specific capabilities.
