### ISSUE TITLE
Geckodriver not taking full website screenshot anymore (Selenium C#)

### ISSUE THREAD

**Issue by lucasalvarezlacasa** [mozilla/geckodriver#436]
Hello guys!. I'm using the geckodriver for Selenium in C#. As I understood while reading posts on the Internet, Firefox allowed you to take a full website screenshot. However this seems to have changed over time, since now it only takes a picture of what's visible on the browser.
This is the code that I'm using:

IWebDriver driver = new FirefoxDriver();
driver.Manage().Window.Maximize();
driver.Navigate().GoToUrl(MAIN_URL);
driver.TakeScreenshot().SaveAsFile(ROOT_FOLDER + "\\Screenshots\\" + "another-one.png",   ImageFormat.Png);
driver.Quit();

Are there any workarounds for this situation?
Thanks, Lucas!.

**Comment by jgraham** [comment]
The [spec](https://w3c.github.io/webdriver/webdriver-spec.html#screen-capture) currently says that screenshots should cover the viewport rather than the hypothetical full document. This makes sense because increasingly browsers might not have a render of the full document available and in some cases (infinite scrolling, for example) it doesn't make much sense.

**Comment by jgraham** [comment]
The [spec](https://w3c.github.io/webdriver/webdriver-spec.html#screen-capture) currently says that screenshots should cover the viewport rather than the hypothetical full document. This makes sense because increasingly browsers might not have a render of the full document available and in some cases (infinite scrolling, for example) it doesn't make much sense.
