### ISSUE TITLE
Firefox maximize and sendKeys does not work

### ISSUE THREAD

**Issue by iamjamalkhan** [mozilla/geckodriver#475]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
51.0.1

## Platform
Linux

## Steps to reproduce -
Selenium 3.0.1 with geckodriver 0.14.0. Try to maximize the window after loading url like
                _driver.get( url );
		By by = get_element( "global_nav" );
		_driver.manage().window().maximize();
                _driver.findElement( by ).sendKeys( Keys.F11 );
		 sleep( 2000 );
		_driver.findElement( by ).sendKeys( Keys.F5 );
Neither does the window maximize nor any of keys are getting sent. The same works fine if I use old Firefox version like 31.0 and make marionette false before initializing the driver.

Not Able to Set log level of geckodriver to trace because as of 3.0.1 there seems no way of setting that in Java binding. Please consider this and try to check this issue on your setup.

**Comment by iamjamalkhan** [comment]
Hi,

Can someone please at least acknowledge whether it's an open issue or not ? If yes do we have any workaround ?

**Comment by andreastt** [comment]
Sending the key F11 will not maximise the window in Marionette. This is quite intentional, since automation of the web content should not have repercussions on the operating system at-large. The [WebDriver specification](http://w3c.github.io/webdriver/webdriver-spec.html) states clearly that _Element Send Keys_ should just fire the relevant DOM events which would affect web content. The same applies to F5, which if pressed should reload the document.

You may replace the use of sending F11 and F5 keys with the _Window Maximize_ and _Refresh_ commands.

**Comment by iamjamalkhan** [comment]
Hi,
I am sorry but I saw another issue #496 looks like we have some bug open which is why this does not work or is this something Selenium Java bindings has not yet implemented.

**Comment by andreastt** [comment]
@iamjamalkhan #496 is a duplicate of #440, but neither of them have anything to do with Selenium. Even if the key attribute on the DOM event is set, I doubt that will make a difference.
