### ISSUE TITLE
Geckodriver does not show the version number

### ISSUE THREAD

**Issue by Elmue** [mozilla/geckodriver#510]
When I start the Geckodriver for Windows a Console window will open.
Other drivers like Opera and Chrome immediately show the version number of the driver.

The Geckdriver instead of a usefull versionumber shows cryptic numbers that nobody will understand.

`1488803975278   geckodriver     INFO    Listening on 127.0.0.1:4444`

This is not really intelligent!

Please display the vesion number and remove these cryptic numbers in front of each line.

Additionally would you please explain why there is a 32 bit version and a 64 bit version of the Gecko driver?
I can control both Firefox 32 bit and Firefox 64 bit with the 32 bit Gecko driver.
So why is there a 64 bit driver offered for download?

**Comment by jgraham** [comment]
Why do you want the version number? You can get it by running with `--version`.

**Comment by Elmue** [comment]
All the other drivers show immediately the version number. The Gecko does not.

But it would even be better if I could read the driver's version from C# code.
Therefore it would be necessary to store the version in the VersionInfo of the resources of the EXE file.
It is usual on Windows that you can right click an executable -> Properties and get the version number displayed. Also with C++ or C# code I can read the version number of all executables on Windows.

Exception are the Selenium drivers which do not store the version in the executable.
This is badly programmed.

**Comment by andreastt** [comment]
> I want to see the version after double clicking the driver.exe without entering any command line.
All the other drivers show immediately the version number. The Gecko does not.

Run `geckodriver --version` before invocation every time you run a test.

> The Geckdriver instead of a usefull versionumber shows cryptic numbers that nobody will understand.
> 
> `1488803975278 geckodriver INFO Listening on 127.0.0.1:4444`

The “cryptic number” is a timestamp with the number of milliseconds from Unix Epoch. We print this because it matches the timestamps from the log output of Firefox, making the log output more harmonious. It is also useful to tell the timestamps in the same format as Marionette, as race conditions can sometimes be hard to track down.

> This is not really intelligent!

Please don’t insult my intelligence.

> Additionally would you please explain why there is a 32 bit version and a 64 bit version of the Gecko driver?
> I can control both Firefox 32 bit and Firefox 64 bit with the 32 bit Gecko driver.
> So why is there a 64 bit driver offered for download?

So you have no need for the 64-bit Windows binary because your 64-bit system has 32-bit emulation support and you prefer to use this binary. Why is it a problem that we offer 64-bit binaries to users _without_ 32-bit emulation?

> But it would even be better if I could read the driver's version from C# code.

Again, you can shell out and capture the stdout from `geckodriver --version`.

> It is usual on Windows that you can right click an executable -> Properties and get the version number displayed.

This is a fair point, but I don’t know how to set this from Rust.

**Comment by Elmue** [comment]
Hello Andreas

Thanks for the explanations.

>Run geckodriver --version before invocation every time you run a test.

This is not a solution for me because the console is a relict from the 1970's and in my software I use the console in NO place. Typing a commandline is (apart from Linux folks who got stuck in the past) used in no place in Windows since the 1990's. In Windows you use modern technologies for inter process communication, like pipes or maybe a TCP connection but the console is dead. 

And parsing the text output from another application is a no-go. Tomorrow the Gecko developers will decide to print the version number slightly different and my text parser to extract the version number will fail. The only correct solution is a well defined binary format to transfer data between applications (or something as XML, but also well defined).

> This is a fair point, but I don’t know how to set this from Rust.

I don't know neither. In this case another tool could modify the already compiled EXE and insert a resource file. 

In reality it is incredible that the Selenium Developers forgot to implement a command to obtain the driver version directly in code in my automating application from the driver. It is also incredible that I cannot get the browser version directly in my C# code from the driver. This is really a lack in the Selenium design.
_________________________________________________________________

So you confirm that I can control both Firefox 32 and 64 with the Geckodriver 32.
In this case the 64 bit driver is not required because ALL 64 bit Windows operating systems have a 32 bit emulation (WOW).

This should be documented because normally the existence of 2 drivers means that you need the 64 bit driver to control the 64 bit browser. In case of Internet Explorer you really need the 64 bit version if you have to automate a 64 bit browser. In case of Gecko the download of the 64 bit driver should be eliminated to avoid this confusion. At least there should be a comment on the download page explaining this!

**Comment by andreastt** [comment]
> This is not a solution for me because the console is a relict from the 1970's and in my software I use the console in NO place.

I wasn’t suggesting you use the shell. You mentioned you were calling geckodriver from C#. Starting a subprocess and capturing its stdout is a perfectly fine way to get information from another program.

> And parsing the text output from another application is a no-go. Tomorrow the Gecko developers will decide to print the version number slightly different and my text parser to extract the version number will fail.

So if it was printed in the log, how would you go about extracting it? Presumably that would involve some form of text parsing.

> The only correct solution is a well defined binary format to transfer data between applications (or something as XML, but also well defined).

We don’t expose the driver version as part of the returned capabilities because it’s not desirable to gate on version numbers. As with the web platform, version sniffing should be avoided in favour of feature sniffing.

> I don't know neither. In this case another tool could modify the already compiled EXE and insert a resource file.

I’m going to say that we are happy to accept a patch for this.

> In reality it is incredible that the Selenium Developers forgot to implement a command to obtain the driver version directly in code in my automating application from the driver. It is also incredible that I cannot get the browser version directly in my C# code from the driver. This is really a lack in the Selenium design.

Driver versions doesn’t mean much. geckodriver is just an HTTP proxy frontend that proxies calls to the Marionette remote control protocol, where most of WebDriver is implemented. What you probably care about here is the _Firefox version_, which you _can_ get through the `browserVersion` capability that is returned when you create a session.

>  In this case the 64 bit driver is not required because ALL 64 bit Windows operating systems have a 32 bit emulation (WOW).

I don’t think that is a strong argument for _not distributing_ a 64-bit binary. Not running in 32-bit emulation mode on a 64-bit system seems like a distinct advantage, as well as the many upsides that a 64-bit architecture gives.

> This should be documented because normally the existence of 2 drivers means that you need the 64 bit driver to control the 64 bit browser. 

This is not true. geckodriver communicates with Firefox over a TCP socket, which is not bound to process architecture.

**Comment by Elmue** [comment]
> This is not true. geckodriver communicates with Firefox over a TCP socket, 
> which is not bound to process architecture.

You did not read my message thoroughly.
"Normally" means: in other cases. I was not talking about Gecko.

In case of Internet Explorer we have driver code running INSIDE of the Internet Explorer process which is a completely different thing. For Internet Explorer we need the correct bitness of the driver: 32 bit browser: 32 bit driver, 64 bit browser: 64 bit driver.

In case of Gecko the 32 bit driver can manage both browsers. So there should be a hint on the download page explaining that the 64 bit version is just for fun, but not required as it is for other browers.

> Not running in 32-bit emulation mode on a 64-bit system seems like a 
> distinct advantage, as well as the many upsides that a 64-bit architecture gives.

The !ONLY! advantage of compiling for 64 bit is that you can address more then 4 Gigabyte of memory.
That is absolutely all.  This is usefull for server applications that work with much memory. For a Gecko driver it is completely irrelevant if it runs as a 32 or 64 bit process. There is absolutely no disadvantage using the 32 bit driver to control a 64 bit browser.

**Comment by dayalanpraveen** [comment]
Hello andreas,
    I am working on a cross-browser scripting using selenium.  For that i need to know my firefox version.  i am using the gecko driver. I can able to get the browser name but i cannot able to get the version number for firefox. 

Thanks

**Comment by andreastt** [comment]
> I am working on a cross-browser scripting using selenium. For that i need to know my firefox version. i am using the gecko driver. I can able to get the browser name but i cannot able to get the version number for firefox.

The Firefox version number is returned in the resolved capabilities object after you start a session. Look for the `browserVersion` field.

**Comment by stestqa** [comment]
Hi Andreas, I realise that you don't want people gating on geckodriver version, but it's still useful information to have in test logs. If a test passed on one machine but failed on another (or on different days/months etc), comparing geckodriver versions would help with troubleshooting.

If geckodriver is running locally then extracting the version from 'geckodriver --version' would suffice, but in most cases we are running via selenium server and the test doesn't (and shouldn't need to) know where the driver binary is located.

Chromedriver returns its version in the resolved capabilities. It would be great if geckodriver could do the same.

**Comment by andreastt** [comment]
@stestqa There’s no standard way of returning the _driver_ version number. In theory, the implementation of WebDriver should be a technicality; it just happens that most vendors implement WebDriver as a two-component solution: one piece which provides the HTTPD (geckodriver/chromedriver/safaridriver) and one that sits inside the browser (Marionette/remote protocol).

My argument earlier was that at least in the future, you should not have to know what version of geckodriver you are using because they will all be both forward- and backwards compatible. The implementation of WebDriver for Firefox is done in Marionette, and geckodriver merely provides the HTTP interfaces.
