### ISSUE TITLE
Firefox crash on using driver.Quit()

### ISSUE THREAD

**Issue by DLemberger** [mozilla/geckodriver#639]
In order to help us efficiently investigate your issue, please provide the following information:

## Firefox Version
52.0.2 (64-Bit)

## Platform
Windows 8.1 Enterprise
64 Bit

## Geckodriver Version

geckodriver-v0.15.0-win64

## Steps to reproduce -

I have made a video of the full process https://www.youtube.com/watch?v=-t5CDOSutOk&feature=youtu.be

Basically, what I do is start an XUnit Test with Selenium Elements - start a web driver, open a site where I log in and then close it after login.

driver.Close() works but doesn't close the website / geckodriver

driver.Quit() closes Firefox with the shown Error
![geckodriver](https://cloud.githubusercontent.com/assets/11227084/24955817/4c496d2e-1f85-11e7-94a7-7594073ae6e5.jpg)

**Comment by andreastt** [comment]
This should be resolved by https://github.com/mozilla/geckodriver/pull/590.

**Comment by DLemberger** [comment]
my flash is standard off because it interfered with tests - so this is not the problem in my case

**Comment by andreastt** [comment]
OK, well I can’t guess what’s wrong from a screenshot. Let me know when you find out what’s wrong so we can re-open this.

**Comment by DLemberger** [comment]
Is the debugging output from the Mozilla Error helping in any form?

C:\Program Files\Mozilla Firefox\mozglue.pdb: Cannot find or open the PDB file.
C:\Program Files\Mozilla Firefox\mozglue.pdb: Cannot find or open the PDB file.
c:\builds\moz2_slave\m-rel-w64-00000000000000000000\build\src\obj-firefox\mozglue\build\mozglue.pdb: Cannot find or open the PDB file.
C:\WINDOWS\mozglue.pdb: Cannot find or open the PDB file.
C:\WINDOWS\symbols\dll\mozglue.pdb: Cannot find or open the PDB file.
C:\WINDOWS\dll\mozglue.pdb: Cannot find or open the PDB file.
----------------
Unhandled exception at 0x00007FFE47E90AE2 (mozglue.dll) in firefox.exe: 0xC0000005: Access violation writing location 0x0000000000000000.
-----------------
Dont really know how i should / can find out whats wrong here, when i call the driver.quit() function

**Comment by whimboo** [comment]
Some thoughts regarding the code/video which I see in the original comment...

The test doesn't open a new window but calls `Close()`, which would cause geckodriver to automatically send a `Quit()` to Firefox. There was a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1337743) in Marionette which could have been caused such a shutdown crash. But it got fixed and is already available for the Firefox 54.0 b1 release.

So please grab this latest beta and try again. I'm sure it will be fixed. If yes it makes this issue a dupe of #285.

**Comment by Nitrokitty** [comment]
I know no one has reported on this in a while but I'm still seeing this issue even with flash disabled (it doesn't even exist in the plugins anymore). I've also looked at https://github.com/SeleniumHQ/selenium/issues/3822. Suppressing the error prevented the dialog from showing but didn't prevent it from actually crashing.  I've suppressed the error messages on all of of our servers. If I run tests one by one, it's fine; no crash & no error message. If I run 16 in parallel (evenly distributed across the servers; the same number we run for chrome without a problem), most if not all of the Firefox browsers crash leaving both the browser and the driver open when calling driver.Quit(). I've also tried closing the window, driver.Close(), before quitting the driver to be more explicit but that hasn't worked either. I would say that it's an issue that should be directed to Mozilla but running tests one by one works fine so I'm not entirely sure that the issue is the browser. Also, running the tests on just one server instead of distributing them works fine as well. I included a snapshot of the error I'm getting in the console.

**Specs:**
- OS: 4 Windows 7 Enterprise Servers (32-bit)
- IDE: Visual Studios 2017 v15.2
- Selenium Server: v3.5.2
- FireFox: v55.0.3 (32-bit)
- Geckodriver: v0.18.0

![image](https://user-images.githubusercontent.com/15735852/29892630-494695f8-8d9d-11e7-962f-185ff6234bc8.png)

**Comment by whimboo** [comment]
So there are several things to mention here... First, if there is a content crash in Firefox which seems to have happened here we mostly hang for a while until Firefox gets killed by geckodriver. Can you please check if that is the case for you? With [bug 1388249](https://bugzilla.mozilla.org/show_bug.cgi?id=1388249) being fixed for the next geckodriver release we will shutdown Firefox immediately. 

Further could you try using the latest Nightly build of Firefox and check if the crash for `Quit` still persists? Build can be found here: https://www.mozilla.org/en-US/firefox/channel/desktop/

When you run the test please record a trace level log (https://github.com/mozilla/geckodriver#capabilities-example), and attach it as attachment. Something I'm interested to know is how long it takes until Firefox crashes after the `quit` command has been sent.

I would suggest that you give feedback on issue #650. Thanks.

**Comment by mgavilan** [comment]
Dear DLemberger,

did you already stumble across the issue with new multi-process architecture for new Firefox releases?

Details and probable (temporary) solutions are mentione here: [https://github.com/mozilla/geckodriver/issues/517](https://github.com/mozilla/geckodriver/issues/517). At least for me, as I also faced this Firefox crashes with driver.quit(), this solved the problem.

Regards
Marcos

**Comment by andreastt** [comment]
FWIW the “Error parsing extension state” thing is nothing to worry about.
