### ISSUE TITLE
WebdriverIO (Selenium): setValue function throws error in Firefox 53.0

### ISSUE THREAD

**Issue by emilbader** [mozilla/geckodriver#673]
## Firefox Version
53.0

## Platform
MacOS Sierra (10.12.4)
Selenium 3.3.1
Geckodriver 0.15

## Steps to reproduce
I started by opening an issue over at WebdriverIO's repository but comments claim the issue lies with Geckodriver. Please see all information (including how to reproduce and logs) regarding this problem [here](https://github.com/webdriverio/webdriverio/issues/1999).

**Comment by andreastt** [comment]
Thanks for your bug report, but this was https://github.com/mozilla/geckodriver/issues/659, which was fixed in 0.16.0. You will need Selenium 3.4 or greater, which sends `{text: "string"}` instead of `{value: ["s", "t", "r", "i", "n", "g"]}`.

The change was made to bring geckodriver closer to [W3C WebDriver](https://w3c.github.io/webdriver/webdriver-spec.html) conformance.
