### ISSUE TITLE
Failed to decode response from marionette - Error to open Webdriver using python

### ISSUE THREAD

**Issue by henriquebin** [mozilla/geckodriver#690]
## Firefox Version
45.5.1
## Platform
 Windows 7 (64bit)
## Other
Selenium Version 3.3.3
GeckoDriver version 0.16.1

## Issue
I'm trying to open a simple Firefox page using selenium webdriver in the python IDLE.
When I run the below command, the Fiferox webdriver open, but I can't execute any other command, as open a link. If I close the window, I get the Marionette exception.

`from selenium import webdriver`
`browser = webdriver.Firefox()`

![image](https://cloud.githubusercontent.com/assets/26934888/25453722/7132de56-2aa0-11e7-935b-54aaf5f59c87.png)

Error:
> Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    browser = webdriver.Firefox()
  File "C:\FAST\Python\3.5.2\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 154, in __init__
    keep_alive=True)
  File "C:\FAST\Python\3.5.2\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "C:\FAST\Python\3.5.2\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 185, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\FAST\Python\3.5.2\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "C:\FAST\Python\3.5.2\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 193, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette

**Comment by andreastt** [comment]
Does this reproduce with Selenium 3.4 or greater? I notice you’re using Firefox 45.5.1, which is not supported by geckodriver. Please see the [section on supported Firefoxen](https://github.com/mozilla/geckodriver#supported-firefoxen) in the README.

It would be helpful if you tried again with [Firefox Nightly](https://www.mozilla.org/en-US/firefox/channel/desktop/#nightly), geckodriver 0.16.1 or greater, and Selenium 3.4 or greater. If it still does not work, please attach a trace-level geckodriver log. The README contains helpful information on how to crank up the logging verbosity.

**Comment by henriquebin** [comment]
Hi andreastt,
I've installed the Selenium 3.4.1 and I'm using geckodriver 0.16.1 with Firefox 45.5.1 (I can't use other firefox version due to my company license limitation) and now I am getting the following exception:

`selenium.common.exceptions.WebDriverException: Message: Unable to find a matching set of capabilities`

Attached the geckodriver.log [geckodriver.zip](https://github.com/mozilla/geckodriver/files/965274/geckodriver.zip)

Thank you for your help.

**Comment by henriquebin** [comment]
I've tried the below configuration and now it seems working.

`capabilities = webdriver.DesiredCapabilities().FIREFOX`
`capabilities["marionette"] = False`
`browser = webdriver.Firefox(capabilities=capabilities)`

**Comment by andreastt** [comment]
@henriquebin Disabling geckodriver/Marionette is not really a solution. The reason you were getting that error was because Firefox 45.5.1 is not supported. You can see which versions of Firefox are from the README.

**Comment by whimboo** [comment]
Btw. Firefox 45 ESR reaches its end of life soon. So I assume your company will update everyone to Firefox 52 ESR. When this happened you can switch to using GeckoDriver.

**Comment by deepidua** [comment]
I am also facing same issue.

 org.openqa.selenium.WebDriverException: Failed to decode response from marionette
      Build info: version: '3.9.1', revision: '63f7b50', time: '2018-02-07T22:25:02.294Z'

Full Stack Trace:

Driver info: org.openqa.selenium.remote.RemoteWebDriver
      Capabilities {acceptInsecureCerts: false, browserName: firefox, browserVersion: 58.0.1, javascriptEnabled: true, moz:accessibilityChecks: false, moz:headless: false, moz:processID: 103, moz:profile: /tmp/rust_mozprofile.Ago8cF..., moz:webdriverClick: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, platformVersion: 3.10.0-327.36.3.el7.x86_64, rotatable: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}}
      Session ID: 2620c991-3171-4528-ba04-933a43620451
      	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
      	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
      	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
      	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
      	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
      	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
      	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
      	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:160)
      	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
      	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:658)
      	at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:343)
      	at utils.CommonUtilities.getscreenshot(CommonUtilities.java:867)
      	at stepDefinition.Test_Steps.user_Create(Test_Steps.java:386)

Line At 386 : commonutil.getscreenshot(driver, "mari"); // from this I am taking screenshot. This method is working in previous step but failed in this step.

I am using latest firfox version and latest selenium 3.9.

**Comment by xihangalpha** [comment]
I have the same problem with @deepidua. But it happens occasionally (maybe once in a thousand of times).


System:

Firefox 52
Selenium 3.8.1
geckodriver 0.16.0
Windows Vista

**Comment by xihangalpha** [comment]
part of geckodriver.log:

JavaScript error: , line 0: TagError: adsbygoogle.push() error: No slot size for availableWidth=1
JavaScript error: , line 0: TagError: adsbygoogle.push() error: No slot size for availableWidth=1
JavaScript error: resource://gre/modules/AddonManager.jsm, line 1434: NS_ERROR_NOT_INITIALIZED: AddonManager is not initialized
1531107378460	addons.productaddons	INFO	sending request to: https://aus5.mozilla.org/update/3/GMP/52.9.0/20180621064021/WINNT_x86-msvc-x86/zh-CN/esr/Windows_NT%206.0.2.0%20(x86)/default/default/update.xml
1531107379804	addons.productaddons	INFO	Completed downloading document
JavaScript warning: https://g.alicdn.com/secdev/sufei_data/3.5.4/index.js, line 1: Error: WebGL: Disallowing antialiased backbuffers due to blacklisting.
JavaScript error: , line 0: TagError: adsbygoogle.push() error: No slot size for availableWidth=1
console.error: PushService: 
  Failed to drop expired registrations on idle
  UnknownError
JavaScript error: https://googleads.g.doubleclick.net/pagead/ads?client=ca-pub-4972132774612142&output=html&h=90&slotname=6112434919&adk=163489972&adf=868109269&w=767&fwrn=4&fwrnh=100&lmt=1531121625&loeid=40993910&rafmt=1&guci=2.2.0.0.2.2.0&format=767x90&url=https%3A%2F%2Fc3.glgooo.top%2F&flash=0&fwr=0&rh=0&rw=767&resp_fmts=3&wgl=1&adsid=NT&dt=1531121624460&bpp=10&bdt=1578&fdt=768&idt=1024&shv=r20180627&cbv=r20180604&saldr=aa&abxe=1&prev_fmts=728x90&correlator=95579163819&frm=20&pv=1&ga_vid=202087959.1531121625&ga_sid=1531121625&ga_hid=1133850810&ga_fc=0&icsg=174720&dssz=16&mdo=0&mso=0&u_tz=480&u_his=2&u_java=0&u_h=720&u_w=1280&u_ah=689&u_aw=1280&u_cd=24&u_nplug=0&u_nmime=0&adx=0&ady=421&biw=767&bih=472&scr_x=0&scr_y=0&eid=21061122%2C40993900%2C368226401&oid=3&ref=https%3A%2F%2Fc3.glgooo.top%2Fscholar&rx=0&eae=0&fc=528&brdim=%2C%2C47%2C44%2C1280%2C0%2C798%2C569%2C784%2C472&vis=1&rsz=o%7Co%7CpeE%7C&abl=NS&ppjl=t&pfx=0&fu=152&bc=5&ifi=2&xpc=AP2U362yET&p=https%3A//c3.glgooo.top&dtd=1114, line 152: ReferenceError: googqscp is not defined
JavaScript error: , line 0: TagError: adsbygoogle.push() error: No slot size for availableWidth=1
JavaScript error: resource://gre/modules/LoginManagerParent.jsm, line 106: TypeError: this._recipeManager is null
1531174100800	geckodriver::marionette	ERROR	Failed to kill browser process

**Comment by xihangalpha** [comment]
@whimboo, do you have any suggestion?

**Comment by andreastt** [comment]
Please let’s not hijack old, resolved issues. If you think you are having a real issue, please submit a trace-level log in a new issue so that we don’t mix up potentially different problems.
