### ISSUE TITLE
Creating a session returns malformed response

### ISSUE THREAD

**Issue by nkovacs** [mozilla/geckodriver#714]
## Firefox Version
53.0

## Platform
Linux

## Steps to reproduce

1. start geckodriver
2. `curl -d '{"capabilities": {"alwaysMatch": {"acceptInsecureCerts": true}}}' http://localhost:4444/session`

The response looks like this:

```
{"value": {"sessionId":"...","capabilities":{...}}}
```

It's supposed to look like this according to the spec (https://w3c.github.io/webdriver/webdriver-spec.html#new-session):

```
{"sessionId":"...","capabilities":{...}}
```

I tried to use geckodriver standalone with nightwatch.js. It fails to create a session [because the response object doesn't have a sessionId key](https://github.com/nightwatchjs/nightwatch/blob/v0.9.15/lib/index.js#L475).

**Comment by nkovacs** [comment]
Looks like it was caused by this: https://github.com/mozilla/webdriver-rust/commit/ac127928a40b689eb69a616fdb3b73f69a1e8617

**Comment by andreastt** [comment]
The return values from a command’s remote end steps are later passed to (‘send a response’]https://w3c.github.io/webdriver/webdriver-spec.html#dfn-send-a-response), which puts the returned data inside a `{"value": <data>}` encapsulation. The steps are described in the [Processing Model](https://w3c.github.io/webdriver/webdriver-spec.html#processing-model) chapter.

The changes in https://github.com/mozilla/webdriver-rust/commit/ac127928a40b689eb69a616fdb3b73f69a1e8617 are expected to bring geckodriver (and the webdriver crate) closer to W3C WebDriver conformance.

If nightwatch.js is failing because of this, it is because it isn’t updated to parse responses from W3C WebDriver conforming drivers yet. Did you raise an issue with them yet?

**Comment by nkovacs** [comment]
I assumed geckodriver was wrong, because selenium, phantomjs/ghostdriver standalone and chromedriver standalone all return the old format, so I didn't read the spec thoroughly enough. And I misinterpreted the commit message.

I'll open an issue for nightwatch.

Thanks.

**Comment by andreastt** [comment]
Yes, neither of those are W3C WebDriver conforming. Selenium is making strides to support WebDriver, but geckodriver is currently the only conforming implementation. Because Selenium provides a backwards compatibility shim, it converts requests made by Selenium clients to W3C WebDriver remotes when it discovers they are not WebDriver conforming. This explains why you are not seeing this issue when operating geckodriver through the Selenium remote server, but you are when you talk to geckodriver standalone. (-:
