### ISSUE TITLE
Firefox 53 - Selenium 3.4.3 - ActionChains not working

### ISSUE THREAD

**Issue by fuuman** [mozilla/geckodriver#778]
In order to help us efficiently investigate your issue, please provide the following information:

## Platform and application details
* Platform: Manjaro
* Firefox: 53.0.3 (64-bit)
* Selenium: 3.4.3

## Steps to reproduce
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium import webdriver
profile = webdriver.FirefoxProfile()
caps = DesiredCapabilities.FIREFOX
driver = webdriver.Firefox(capabilities=caps, firefox_profile=profile)
driver.get("about:blank")
ActionChains(driver).key_down(Keys.F12).key_up(Keys.F12).perform()

## Result
perform() returns None and there is no open inspector in my Firefox.

**Comment by andreastt** [comment]
WebDriver is not meant to allow interaction with the browser chrome or the surrounding system widgets (OS), so I would say this is entirely expected behaviour.  By pressing F12 like you do, I would expect there to be a `keydown` and a `keyup` event for that key, but not for devtools to open.

**Comment by fuuman** [comment]
Why are you talking about _chrome_? And with Firefox 46 for example, it worked exactly like that to open the Firefox inspector. How I am able to open the inspector then?

**Comment by andreastt** [comment]
Sorry, the “browser chrome” is the technical term for the UI of a browser.

Firefox 46 was presumably using FirefoxDriver, which was supported by and implemented by the Selenium project. geckodriver is maintained by Mozilla, and is fundamentally different in architecture.

You should not be able to open devtools via geckodriver unless you switch to what’s called ‘chrome context’, but I don’t really know off-hand how to open it from chrome-privileged JS.

**Comment by whimboo** [comment]
To be able to send commands to the chrome scope of Firefox the context has to be switched first. If Python is used as binding you can get some ideas from Foxpuppet: https://github.com/mozilla/FoxPuppet/blob/bd593d59f523a65d67c7630cd34fdbfce688780e/foxpuppet/windows/browser/notifications/base.py#L29.

**Comment by java123code** [comment]
This issue is still reproducible for Firefox. 

VS 2017 , Selenium v 3.12.1 ,C# , Firefox V 60.0.2 , Chrome V 66 , Nunit v3.10.1 , Gecko Driver v 20.1 , chrome driver v 2.4

   I tried to find solution  Firefox but did not success but I do get solution for Chrome v66

    please provide profile like this : options.AddArguments("--auto-open-devtools-for-tabs");


    this is complete chrome driver implementation :


ChromeOptions options = new ChromeOptions();
options.AddArgument("--start-maximized");
options.AddArguments("disable-infobars");
options.AddArguments("--disable-notifications");
options.AddArguments("--auto-open-devtools-for-tabs");
driver = new ChromeDriver(DrivePath, options, TimeSpan.FromSeconds(100));


    you may have a look here as well : 

    https://peter.sh/experiments/chromium-command-line-switches/


Below commands are NOT working, this is issue with Geckodriver so Gecko team has to provide some solution or fix for that :

driver.FindElement(By.CssSelector("body")).SendKeys(Keys.F12);

Actions action = new Actions(driver); action.SendKeys(Keys.F12); action.Perform();

Actions action = new Actions(driver); action .KeyDown(Keys.Control).SendKeys(Keys.F12).KeyUp(Keys.Control).Perform();

Actions action = new Actions(driver); action.SendKeys(Keys.F12); action.Click();

**Comment by whimboo** [comment]
@java123code please do not cross-post the same question across different issues. As already mentioned on issue #646 your problem is not related to both of these issues.
