### ISSUE TITLE
Get Element Text has to work on rendered text

### ISSUE THREAD

**Issue by AohRveTPV** [mozilla/geckodriver#802]
## Platform and application details
* Platform: Windows 7
* Firefox: 54
* Selenium: 3.4.0

## Steps to reproduce
1. Try to find element by its CSS text-transformed link text.  For example, with the testcase below and the Python Selenium bindings, ```driver.find_element_by_link_text("FOO")```.

The element cannot be found.  However, the same code finds the element with Chrome and IE.  If I change it to ```driver.find_element_by_link_text("Foo")```, it works in Firefox but not Chrome and IE.

The WebDriver specification, section 13.5, says:
> The Get Element Text command intends to return an element’s text “as rendered”.

To me, it seems the text as rendered is "FOO" not "Foo".

- [x] Reproducable testcase:
```
<!DOCTYPE html>
<html>
  <head>
    <title>Foo</title>
  </head>
  <body>
    <a href="/foo/bar" style="text-transform: uppercase">Foo</a>
  </body>
</html>     
```

- [x] A trace level log:
I'm using Sauce Labs--not my own Selenium and geckodriver installation--and I'm not sure how to obtain a trace level log.  Any guidance would be appreciated.

Finally, apologies if this is not the correct project for this issue. Since it affects only Firefox, I assumed it was related to geckodriver.

**Comment by andreastt** [comment]
This is a known problem with the WebDriver specification. We cannot rely on `innerText` because only Firefox implements it according to the specification AFAIK. Because we want to achieve conformance with other WebDriver implementations, we are currently using a Selenium JS atom, which is known not to take `text-transform`, or indeed nearly any CSS properties, into account.

**Comment by jgraham** [comment]
I think that's not true? From my cursory reading of the selenium code linked in the spec it looks like it does try to account for the text-transform and whitespace properties.

**Comment by andreastt** [comment]
We may likely be using an outdated version of the Selenium atom (it is hard to update because we don’t know exactly how to build it in the format Marionette expects), so it would be interesting if would be useful if you would verify that this use case works in practice with the Selenium atom from upstream.

**Comment by whimboo** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1381519 to cover the Marionette issue.

**Comment by whimboo** [comment]
Btw this got already fixed about a month ago for Firefox 61.
