### ISSUE TITLE
Add a "LATEST.json" file to repo

### ISSUE THREAD

**Issue by gauntface** [mozilla/geckodriver#87]
To automatically grab the latest release I have to make an API call to github to find out all the releases and pull out the latest build. This is fine but I keep hitting the rate limit from Github, having a file of some sort that points to the latest build would be super helpful.

**Comment by andreastt** [comment]
@gauntface If you have a local checkout of the repository you can get the latest version by `git tag -l | tail -1`.

**Comment by andreastt** [comment]
@gauntface A better solution might be:

    % git ls-remote -t https://github.com/mozilla/geckodriver | tail -1 | grep -Eo 'v[0-9]+\.[0-9]+\.[0-9]+'
    v0.8.0

**Comment by gauntface** [comment]
At the moment I'm working on a node tool to make grabbing and using this stuff a little easier so I could wrap that in a shell script and call it from Node.

What is the end goal of distribution for this? NPM? Firefox? Selenium Libraries?

**Comment by andreastt** [comment]
That is a good question I don’t think we’ve talked about. Marionette, the WebDriver implementation, ships inside Gecko and is frequently updated. The geckodriver binary (from this repository) implements just the HTTP front-end and will presumably not need to change as often once it’s stable. Currently I’d say the model is that we expect people to download it from here.

The Selenium project decided a while back that they don’t want vendor specific libraries, binaries, or code to live inside their project because it imposes a certain maintenance burden on them.

It’s an interesting idea to ship it alongside Firefox, which is something similar I think to what Apple is [planning to do](https://developer.apple.com/library/prerelease/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_0.html) with their safaridriver. I personally think it would be excellent if we could do that with geckodriver, but it hinges on build system integration with Cargo and the Rust toolchain, which I understand is still a bit into the future. (You can see some of the discussion around that in [bug 1275230](https://bugzilla.mozilla.org/show_bug.cgi?id=1275230).)

I’m sure @AutomatedTester will have some useful input on this.

**Comment by andreastt** [comment]
I’m going to close this issue as we have no plan to add a LATEST.json file to the repo, but I welcome more discussion around how to do distribution of this program. The short time solution will be through downloads from Github Releases, but I’m really warming to the idea of distributing it together with the Firefox binary in the future (pending [cargo integration](https://bugzilla.mozilla.org/show_bug.cgi?id=1275230) in mozilla-central).
