### ISSUE TITLE
[Re] Request Maintain An Stable Geckodriver For Certain Firefox Version

### ISSUE THREAD

**Issue by Kenith** [mozilla/geckodriver#885]
Hello All,

As we know, the Firefox 55.0.2 is released. 
We believe that every automation tester could find that,  every time the new Firefox version is released, the current latest Geckodriver could encounter some issues when trying to interaction with the new Firefox.

Therefore, from here, we sincerely to ask you that whether it is possible to build a stable version for few version of Firefox. For example:
- Firefox 50.x, Geckodriver 0.15 Stable
- Firefox 51.x, Geckodriver 0.16 Stable
- Firefox 54.x, Geckodriver 0.17 Stable
...

Thank you,
Ken

**Comment by andreastt** [comment]
We try to ensure compatibility with the release channels of Firefox (stable, beta, nightly), but there are two important facts to remember here: geckodriver itself is only a proxy that relays commands to the Marionette remote protocol in Firefox, and geckodriver is at the moment in a pre-release state.

The first means that most bug fixes and improvements are tied to the Firefox version you use. The more recent the Firefox version, generally the better the conformance with the WebDriver specification. It doesn’t make sense to tie one specific version of geckodriver to a specific release of Firefox like chromedriver does, because the two communicate over a transparent protocol. Once geckodriver reaches maturity (a 1.0 release), we will become more rigorous about our backwards compatibility with earlier Firefoxen.
