### ISSUE TITLE
testAnElementFoundInADifferentFrameIsStale fails in Nightly

### ISSUE THREAD

**Issue by barancev** [mozilla/geckodriver#934]
## System
* Version: 0.18
* Platform: Windows 7
* Firefox: 57.0a1 (2017-09-03) (64-bit)
* Selenium: 3.5.3 Java

## Testcase
testAnElementFoundInADifferentFrameIsStale in Selenium Java test suite, or
```
driver.get("https://www.theguardian.com/us");
driver.switchTo().frame(driver.findElement(By.cssSelector(".youtube-media-atom__iframe")));
WebElement player = driver.findElement(By.cssSelector("#player"));
driver.switchTo().defaultContent();
String text = player.getText();
```
Note the last line, an attempt to get text of an element that does not belong to the currently selected frame.

This operation used to throw StaleElementRefernceException in OSS Selenium drivers, it throws in Firefox 55 + geckodriver 0.18, but it does *not* throw in Nightly 57.0a1.

**Comment by AutomatedTester** [comment]
@andreastt I think this might be related to the `element.isConnected()` work you did recently. Can you add your thoughts please?

**Comment by andreastt** [comment]
@AutomatedTester Should have been fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1395469. Please confirm.

**Comment by joshbruning** [comment]
If it helps, this issue exists in:

Version: 0.19
Platform: Linux
Firefox: 57.0b3 (64-bit)
Selenium: 3.5.3 Java

**Comment by whimboo** [comment]
@barancev mind also testing if you case works now with the latest Nightly and first 57b3 release? If yes, @joshbruning should file a new issue for his case with more detail what doesn't work. Thanks.

**Comment by joshbruning** [comment]
I ran the same test that @barancev suppressed in:
https://github.com/SeleniumHQ/selenium/commit/cc0066ffa04c7cf7561b2acdd0ee1de99618475b
Will watch this issue to see if @barancev can still repro.

**Comment by barancev** [comment]
The test fails in Nightly 58.0a1 (2017-09-28) (64-bit)

**Comment by whimboo** [comment]
Thanks! @andreastt looks like that there is one more fallout from your staleness changes in 57. Can you please check it again the next days?

**Comment by andreastt** [comment]
Thanks for the test case. I’ve translated it into a Marionette test:

```py
from marionette_harness import MarionetteTestCase

class TestFoo(MarionetteTestCase):
    def test_foo(self):
        self.marionette.navigate("https://www.theguardian.com/us");
        frame = self.marionette.find_element("css selector", ".youtube-media-atom__iframe")
        self.marionette.switch_to_frame(frame=frame)
        player = self.marionette.find_element("css selector", "#player")
        self.marionette.switch_to_default_content()

        # should throw
        text = player.text
```

This problem is tricky because [`element.isStale`](https://searchfox.org/mozilla-central/rev/298033405057ca7aa5099153797467eceeaa08b5/testing/marionette/element.js#628-652) doesn’t take the WebDriver-selected current browsing context into mind.

The intention of [the original change](https://hg.mozilla.org/mozilla-central/rev/d73e79c0d9d4) was to not have to pass the `WindowProxy` reference into `seenEls.get(…)` to make the known element store easier to integrate into the upcoming [window tracking](https://bugzilla.mozilla.org/show_bug.cgi?id=marionette-window-tracking) changes, but it did not take into account the frame case, where the element’s document still exists but is different from the current browsing context selected by WebDriver.

I’ve filed https://bugzilla.mozilla.org/show_bug.cgi?id=1405018 to track this.
