### ISSUE TITLE
Selenium calls Get Element Attribute when it means to call Get Element Property

### ISSUE THREAD

**Issue by Toilal** [mozilla/geckodriver#95]
When using MarionetteDriver in Selenium 2.53, ```getAttribute("textContent")``` always returns null.

With FirefoxDriver on firefox 46, it gives the effective text content.

(I'm not sure it's a geckodriver or Selenium issue)

**Comment by jgraham** [comment]
`textContent` is a DOM property not a element attribute, so you need to call something that maps to the [Get Element Property](https://w3c.github.io/webdriver/webdriver-spec.html#get-element-property) command in the spec. I am not sure how this is exposed in the Selenium client.

**Comment by andreastt** [comment]
I filed https://github.com/SeleniumHQ/selenium/issues/2301 about implementing a shim in existing Selenium client bindings to patch over this.

**Comment by Toilal** [comment]
Currently, in others drivers like FirefoxDriver, HtmlUnitDriver, ChromeDriver, there are some "magical" key on getAttribute parameter to retrieve some element attribute, like textContent or value ... It sounds really weird, but that's how it works currently in Selenium 2.53.

See this test : [ElementAttributeTest.java](https://github.com/SeleniumHQ/selenium/blob/c10e8a955883f004452cdde18096d70738397788/java/client/test/org/openqa/selenium/ElementAttributeTest.java#L255-L265)

**Comment by andreastt** [comment]
@Toilal They’re not “magical”. If I remember correctly Selenium first looks to see if the requested property exists and returns that if it does, otherwise it returns the attribute value.

The WebDriver specification split the API into one for [getting attributes](http://w3c.github.io/webdriver/webdriver-spec.html#get-element-attribute) and one for [getting properties](http://w3c.github.io/webdriver/webdriver-spec.html#get-element-property). It is possible to patch over this in the Selenium client libraries to not break existing tests when using a WebDriver conformant implementation, such as Marionette/geckodriver.

**Comment by Toilal** [comment]
Thanks for your explanations.

**Comment by Toilal** [comment]
After more tests, it seems them problem only occurs with Firefox Nightly 50.0a1 (2016-06-16). Running the test under firefox 47 works find (```getAttribute("textContent")``` returns the textContent element property).

**Comment by andreastt** [comment]
Yes, the spec compatible Get Element Attribute and Get Element Property commands were added quite recently in bug 1272653. It is available in Firefox 48, Firefox 49, and Nightly.

**Comment by Toilal** [comment]
I tried this again with Firefox 49.0.1 and can't reproduce the issue. getAttribute("textContent") returns the text content as expected.
